
INSERT INTO `1_antonym` (`id`, `word`, `type`, `question`, `correct_answer`, `wrong_answer1`, `wrong_answer2`, `wrong_answer3`, `explanation`) VALUES
(1, 'scarce', 'Antonym', 'What is the antonym of scarce?', 'abundant', 'rare', 'limited', 'insufficient', 'Scarce means lacking in quantity; abundant means plentiful.'),
(2, 'conceal', 'Antonym', 'What is the antonym of conceal?', 'reveal', 'cover', 'hide', 'mask', 'Conceal means to hide; reveal means to make visible or known.'),
(3, 'rigid', 'Antonym', 'What is the antonym of rigid?', 'flexible', 'hard', 'stiff', 'solid', 'Rigid means inflexible or stiff; flexible means capable of bending.'),
(4, 'prosperity', 'Antonym', 'What is the antonym of prosperity?', 'poverty', 'wealth', 'growth', 'luxury', 'Prosperity is a state of success and wealth; poverty is a state of lack.'),
(5, 'ally', 'Antonym', 'What is the antonym of ally?', 'enemy', 'partner', 'supporter', 'friend', 'An ally is someone who supports; an enemy is someone who opposes.'),
(6, 'expand', 'Antonym', 'What is the antonym of expand?', 'contract', 'enlarge', 'grow', 'develop', 'Expand means to increase in size; contract means to shrink.'),
(7, 'optimistic', 'Antonym', 'What is the antonym of optimistic?', 'pessimistic', 'hopeful', 'cheerful', 'joyful', 'Optimistic means expecting the best; pessimistic means expecting the worst.'),
(8, 'scarcity', 'Antonym', 'What is the antonym of scarcity?', 'plenty', 'shortage', 'insufficiency', 'lack', 'Scarcity means a shortage; plenty means more than enough.'),
(9, 'complexity', 'Antonym', 'What is the antonym of complexity?', 'simplicity', 'difficulty', 'density', 'variety', 'Complexity means being complicated; simplicity means being easy or straightforward.'),
(10, 'dominate', 'Antonym', 'What is the antonym of dominate?', 'submit', 'control', 'lead', 'excel', 'To dominate is to have power over; to submit is to yield or surrender.'),
(11, 'rigorous', 'Antonym', 'What is the antonym of rigorous?', 'lenient', 'strict', 'severe', 'intense', 'Rigorous means very strict or severe; lenient means more forgiving.'),
(12, 'vivid', 'Antonym', 'What is the antonym of vivid?', 'dull', 'bright', 'intense', 'colorful', 'Vivid means full of life or color; dull means lacking brightness.'),
(13, 'internal', 'Antonym', 'What is the antonym of internal?', 'external', 'deep', 'inside', 'inner', 'Internal refers to the inside; external refers to the outside.'),
(14, 'advance', 'Antonym', 'What is the antonym of advance?', 'retreat', 'progress', 'approach', 'move', 'To advance is to move forward; to retreat is to move back.'),
(15, 'approve', 'Antonym', 'What is the antonym of approve?', 'reject', 'support', 'accept', 'allow', 'To approve is to agree or accept; to reject is to decline.'),
(16, 'frequent', 'Antonym', 'What is the antonym of frequent?', 'rare', 'common', 'usual', 'constant', 'Frequent means happening often; rare means happening infrequently.'),
(17, 'hostile', 'Antonym', 'What is the antonym of hostile?', 'friendly', 'rude', 'angry', 'aggressive', 'Hostile means unfriendly or aggressive; friendly means kind and welcoming.'),
(18, 'expandable', 'Antonym', 'What is the antonym of expandable?', 'fixed', 'extendable', 'elastic', 'extendable', 'Expandable means capable of increasing in size; fixed means unchanging.'),
(19, 'clarify', 'Antonym', 'What is the antonym of clarify?', 'confuse', 'explain', 'define', 'simplify', 'To clarify is to make something clear; to confuse is to make it unclear.'),
(20, 'exterior', 'Antonym', 'What is the antonym of exterior?', 'interior', 'outside', 'surface', 'visible', 'Exterior refers to the outside; interior refers to the inside.'),
(21, 'departure', 'Antonym', 'What is the antonym of departure?', 'arrival', 'exit', 'leave', 'migration', 'Departure means leaving; arrival means coming.'),
(22, 'include', 'Antonym', 'What is the antonym of include?', 'exclude', 'add', 'mention', 'cover', 'To include means to contain; to exclude means to leave out.'),
(23, 'generosity', 'Antonym', 'What is the antonym of generosity?', 'selfishness', 'charity', 'kindness', 'openness', 'Generosity is giving freely; selfishness is prioritizing oneself.'),
(24, 'justice', 'Antonym', 'What is the antonym of justice?', 'injustice', 'law', 'fairness', 'truth', 'Justice means fairness and lawfulness; injustice is the absence of fairness.'),
(25, 'extend', 'Antonym', 'What is the antonym of extend?', 'shorten', 'prolong', 'enlarge', 'reach', 'To extend is to make longer; to shorten is to reduce in length.'),
(26, 'permit', 'Antonym', 'What is the antonym of permit?', 'forbid', 'allow', 'grant', 'consent', 'To permit is to allow; to forbid is to prohibit.'),
(27, 'harmony', 'Antonym', 'What is the antonym of harmony?', 'conflict', 'peace', 'balance', 'unity', 'Harmony is peaceful agreement; conflict is disagreement or struggle.'),
(28, 'rapid', 'Antonym', 'What is the antonym of rapid?', 'slow', 'fast', 'swift', 'sudden', 'Rapid means very fast; slow means not moving quickly.'),
(30, 'encourage', 'Antonym', 'What is the antonym of encourage?', 'discourage', 'motivate', 'inspire', 'support', 'Encourage means to give support; discourage means to dissuade or dishearten.'),
(31, 'liberty', 'Antonym', 'What is the antonym of liberty?', 'oppression', 'freedom', 'independence', 'choice', 'Liberty is the state of being free; oppression is being controlled or restricted.'),
(32, 'elevate', 'Antonym', 'What is the antonym of elevate?', 'lower', 'raise', 'lift', 'boost', 'Elevate means to raise; lower means to bring down.'),
(33, 'affirm', 'Antonym', 'What is the antonym of affirm?', 'deny', 'declare', 'confirm', 'state', 'To affirm is to state positively; to deny is to state something is not true.'),
(34, 'visible', 'Antonym', 'What is the antonym of visible?', 'invisible', 'apparent', 'seen', 'clear', 'Visible means able to be seen; invisible means not seen.'),
(35, 'construct', 'Antonym', 'What is the antonym of construct?', 'demolish', 'build', 'form', 'design', 'To construct means to build; demolish means to tear down.'),
(36, 'acceptance', 'Antonym', 'What is the antonym of acceptance?', 'rejection', 'approval', 'agreement', 'welcome', 'Acceptance is approval or consent; rejection is refusal.'),
(37, 'external', 'Antonym', 'What is the antonym of external?', 'internal', 'outside', 'visible', 'outer', 'External refers to the outside; internal refers to the inside.'),
(38, 'composed', 'Antonym', 'What is the antonym of composed?', 'agitated', 'calm', 'collected', 'peaceful', 'Composed means calm and in control; agitated means disturbed or upset.'),
(39, 'glory', 'Antonym', 'What is the antonym of glory?', 'disgrace', 'fame', 'honor', 'victory', 'Glory means honor or admiration; disgrace is loss of respect.'),
(40, 'abundant', 'Antonym', 'What is the antonym of abundant?', 'scarce', 'plentiful', 'ample', 'numerous', 'Abundant means more than enough; scarce means in short supply.'),
(41, 'superior', 'Antonym', 'What is the antonym of superior?', 'inferior', 'excellent', 'strong', 'greater', 'Superior means higher in rank or quality; inferior means lower in rank or quality.'),
(42, 'minimum', 'Antonym', 'What is the antonym of minimum?', 'maximum', 'least', 'smallest', 'lowest', 'Minimum is the smallest amount; maximum is the greatest.'),
(43, 'permanent', 'Antonym', 'What is the antonym of permanent?', 'temporary', 'lasting', 'constant', 'regular', 'Permanent means lasting forever; temporary means lasting for a short time.'),
(44, 'affirmative', 'Antonym', 'What is the antonym of affirmative?', 'negative', 'positive', 'agreeable', 'constructive', 'Affirmative means expressing agreement; negative means expressing denial or disagreement.'),
(45, 'vacant', 'Antonym', 'What is the antonym of vacant?', 'occupied', 'empty', 'clear', 'spacious', 'Vacant means unoccupied; occupied means in use or filled.'),
(46, 'barren', 'Antonym', 'What is the antonym of barren?', 'fertile', 'dry', 'plain', 'empty', 'Barren means not producing; fertile means able to produce abundantly.'),
(47, 'flexible', 'Antonym', 'What is the antonym of flexible?', 'rigid', 'elastic', 'soft', 'movable', 'Flexible means capable of bending; rigid means stiff and inflexible.'),
(48, 'fragile', 'Antonym', 'What is the antonym of fragile?', 'durable', 'breakable', 'delicate', 'fine', 'Fragile means easily broken; durable means strong and long-lasting.'),
(49, 'encounter', 'Antonym', 'What is the antonym of encounter?', 'avoid', 'meet', 'engage', 'approach', 'To encounter means to meet; to avoid means to keep away from.'),
(50, 'prohibit', 'Antonym', 'What is the antonym of prohibit?', 'allow', 'ban', 'limit', 'control', 'To prohibit means to forbid; to allow means to permit.'),
(52, 'cautious', 'Antonym', 'What is the antonym of cautious?', 'reckless', 'careful', 'thoughtful', 'alert', 'Cautious means careful; reckless means without thinking about danger.'),
(53, 'cease', 'Antonym', 'What is the antonym of cease?', 'continue', 'pause', 'stop', 'delay', 'To cease means to stop; to continue means to keep going.'),
(54, 'tame', 'Antonym', 'What is the antonym of tame?', 'wild', 'calm', 'gentle', 'mild', 'Tame means domesticated or controlled; wild means undomesticated or uncontrolled.'),
(55, 'dawn', 'Antonym', 'What is the antonym of dawn?', 'dusk', 'sunrise', 'morning', 'light', 'Dawn is the beginning of daylight; dusk is the end of it.'),
(57, 'support', 'Antonym', 'What is the antonym of support?', 'oppose', 'help', 'approve', 'assist', 'Support means to back or help; oppose means to go against.'),
(59, 'confidence', 'Antonym', 'What is the antonym of confidence?', 'doubt', 'trust', 'belief', 'hope', 'Confidence is a strong belief or trust; doubt is uncertainty or disbelief.'),
(60, 'public', 'Antonym', 'What is the antonym of public?', 'private', 'social', 'open', 'shared', 'Public means open to all; private means restricted or personal.'),
(61, 'transparent', 'Antonym', 'What is the antonym of transparent?', 'opaque', 'clear', 'visible', 'glasslike', 'Transparent means light can pass through; opaque means it cannot.'),
(62, 'mature', 'Antonym', 'What is the antonym of mature?', 'immature', 'grown', 'adult', 'developed', 'Mature means fully developed; immature means not yet fully grown.'),
(63, 'precise', 'Antonym', 'What is the antonym of precise?', 'vague', 'exact', 'sharp', 'strict', 'Precise means exact or accurate; vague means unclear or imprecise.'),
(65, 'satisfy', 'Antonym', 'What is the antonym of satisfy?', 'displease', 'please', 'comfort', 'impress', 'To satisfy means to fulfill or please; to displease means to cause dissatisfaction.'),
(66, 'humble', 'Antonym', 'What is the antonym of humble?', 'arrogant', 'kind', 'respectful', 'quiet', 'Humble means modest; arrogant means having excessive pride.'),
(67, 'sophisticated', 'Antonym', 'What is the antonym of sophisticated?', 'naive', 'cultured', 'elegant', 'refined', 'Sophisticated means cultured or complex; naive means inexperienced or simple.'),
(68, 'promote', 'Antonym', 'What is the antonym of promote?', 'demote', 'advance', 'endorse', 'appoint', 'To promote means to raise in position; demote means to lower in rank.'),
(69, 'voluntary', 'Antonym', 'What is the antonym of voluntary?', 'mandatory', 'optional', 'chosen', 'free', 'Voluntary means done by choice; mandatory means required.'),
(70, 'progress', 'Antonym', 'What is the antonym of progress?', 'regress', 'advance', 'improve', 'succeed', 'Progress means moving forward; regress means moving backward.'),
(72, 'benefit', 'Antonym', 'What is the antonym of benefit?', 'harm', 'gain', 'bonus', 'advantage', 'Benefit means a helpful gain; harm means damage or injury.'),
(73, 'bold', 'Antonym', 'What is the antonym of bold?', 'timid', 'brave', 'strong', 'loud', 'Bold means courageous; timid means shy or lacking confidence.'),
(74, 'fertile', 'Antonym', 'What is the antonym of fertile?', 'barren', 'rich', 'fruitful', 'productive', 'Fertile means able to produce; barren means unproductive.'),
(75, 'complex', 'Antonym', 'What is the antonym of complex?', 'simple', 'difficult', 'detailed', 'diverse', 'Complex means complicated; simple means easy or uncomplicated.'),
(77, 'agree', 'Antonym', 'What is the antonym of agree?', 'disagree', 'approve', 'comply', 'accept', 'To agree means to have the same opinion; to disagree means to have a different one.'),
(78, 'wealth', 'Antonym', 'What is the antonym of wealth?', 'poverty', 'riches', 'affluence', 'fortune', 'Wealth is an abundance of money or resources; poverty is a lack of them.'),
(79, 'import', 'Antonym', 'What is the antonym of import?', 'export', 'receive', 'ship', 'load', 'Import means to bring in goods; export means to send them out.'),
(80, 'arrival', 'Antonym', 'What is the antonym of arrival?', 'departure', 'entrance', 'visit', 'check-in', 'Arrival means coming to a place; departure means leaving it.'),
(81, 'hostility', 'Antonym', 'What is the antonym of hostility?', 'friendliness', 'anger', 'aggression', 'rudeness', 'Hostility means unfriendliness or antagonism; friendliness means kind and welcoming behavior.'),
(82, 'strength', 'Antonym', 'What is the antonym of strength?', 'weakness', 'power', 'toughness', 'endurance', 'Strength refers to power or force; weakness is the lack of strength.'),
(84, 'freedom', 'Antonym', 'What is the antonym of freedom?', 'captivity', 'liberty', 'choice', 'independence', 'Freedom means being free; captivity is being confined or imprisoned.'),
(85, 'consent', 'Antonym', 'What is the antonym of consent?', 'refusal', 'approval', 'agreement', 'acceptance', 'Consent means giving permission; refusal means denying permission.'),
(86, 'reward', 'Antonym', 'What is the antonym of reward?', 'penalty', 'bonus', 'benefit', 'honor', 'A reward is something given for good behavior; a penalty is a punishment for wrongdoing.'),
(87, 'sincere', 'Antonym', 'What is the antonym of sincere?', 'deceitful', 'genuine', 'truthful', 'honest', 'Sincere means honest and genuine; deceitful means lying or misleading.'),
(90, 'intensify', 'Antonym', 'What is the antonym of intensify?', 'weaken', 'amplify', 'grow', 'develop', 'To intensify means to strengthen; to weaken means to reduce in strength.'),
(91, 'deny', 'Antonym', 'What is the antonym of deny?', 'admit', 'refuse', 'decline', 'reject', 'To deny is to declare something is false; to admit is to accept it as true.'),
(92, 'majority', 'Antonym', 'What is the antonym of majority?', 'minority', 'total', 'population', 'dominance', 'Majority means the greater part; minority means the smaller part.'),
(94, 'clarity', 'Antonym', 'What is the antonym of clarity?', 'confusion', 'precision', 'transparency', 'light', 'Clarity means clearness or understanding; confusion means lack of understanding.'),
(96, 'praise', 'Antonym', 'What is the antonym of praise?', 'criticize', 'commend', 'cheer', 'thank', 'To praise is to express approval; to criticize is to point out faults.'),
(101, 'constructive', 'Antonym', 'What is the antonym of constructive?', 'destructive', 'productive', 'useful', 'helpful', 'Constructive means helpful or beneficial; destructive means causing damage.'),
(103, 'precaution', 'Antonym', 'What is the antonym of precaution?', 'risk', 'measure', 'warning', 'concern', 'Precaution is action taken to prevent harm; risk is the exposure to danger.'),
(104, 'wealthy', 'Antonym', 'What is the antonym of wealthy?', 'poor', 'rich', 'famous', 'powerful', 'Wealthy means having a lot of money; poor means having little or none.'),
(105, 'generous', 'Antonym', 'What is the antonym of generous?', 'stingy', 'kind', 'helpful', 'selfless', 'Generous means willing to give; stingy means unwilling to share.'),
(106, 'loyal', 'Antonym', 'What is the antonym of loyal?', 'betraying', 'faithful', 'trustworthy', 'respectful', 'Loyal means faithful and devoted; betraying means acting against someone’s trust.'),
(108, 'increase', 'Antonym', 'What is the antonym of increase?', 'reduce', 'raise', 'improve', 'multiply', 'Increase means to grow in size or amount; reduce means to make smaller.'),
(109, 'victory', 'Antonym', 'What is the antonym of victory?', 'defeat', 'glory', 'achievement', 'reward', 'Victory means success in a struggle; defeat means loss.'),
(110, 'polite', 'Antonym', 'What is the antonym of polite?', 'rude', 'kind', 'respectful', 'formal', 'Polite means showing good manners; rude means disrespectful or impolite.'),
(112, 'maximize', 'Antonym', 'What is the antonym of maximize?', 'minimize', 'expand', 'raise', 'enlarge', 'Maximize means to increase as much as possible; minimize means to reduce as much as possible.'),
(113, 'presence', 'Antonym', 'What is the antonym of presence?', 'absence', 'existence', 'participation', 'attendance', 'Presence means being there; absence means being away.'),
(114, 'create', 'Antonym', 'What is the antonym of create?', 'destroy', 'build', 'form', 'develop', 'To create means to make something; to destroy means to ruin or eliminate it.'),
(116, 'supportive', 'Antonym', 'What is the antonym of supportive?', 'critical', 'encouraging', 'loyal', 'caring', 'Supportive means offering help or encouragement; critical means pointing out faults.'),
(121, 'abandon', 'Antonym', 'What is the antonym of abandon?', 'retain', 'neglect', 'refuse', 'ignore', 'To abandon means to leave behind; to retain means to keep or continue holding.'),
(122, 'advocate', 'Antonym', 'What is the antonym of advocate?', 'oppose', 'support', 'endorse', 'encourage', 'To advocate means to support a cause; to oppose means to go against it.'),
(123, 'deteriorate', 'Antonym', 'What is the antonym of deteriorate?', 'improve', 'decline', 'weaken', 'fail', 'Deteriorate means to become worse; improve means to become better.'),
(126, 'glorious', 'Antonym', 'What is the antonym of glorious?', 'shameful', 'brilliant', 'famous', 'victorious', 'Glorious means bringing great admiration; shameful means causing disgrace.'),
(129, 'liberate', 'Antonym', 'What is the antonym of liberate?', 'confine', 'free', 'release', 'unite', 'To liberate means to set free; to confine means to imprison or restrict.'),
(131, 'oppose', 'Antonym', 'What is the antonym of oppose?', 'support', 'resist', 'reject', 'deny', 'To oppose means to disagree or fight against; to support means to back or promote.'),
(132, 'perish', 'Antonym', 'What is the antonym of perish?', 'survive', 'die', 'suffer', 'weaken', 'Perish means to die or be destroyed; survive means to continue living.'),
(137, 'stability', 'Antonym', 'What is the antonym of stability?', 'chaos', 'balance', 'order', 'peace', 'Stability means consistency or steadiness; chaos is complete disorder.'),
(138, 'tolerate', 'Antonym', 'What is the antonym of tolerate?', 'reject', 'accept', 'endure', 'allow', 'To tolerate means to endure or accept; to reject means to refuse or deny.'),
(141, 'absent', 'Antonym', 'What is the antonym of absent?', 'present', 'away', 'missing', 'vacant', 'Absent means not being there; present means being there.'),
(142, 'assemble', 'Antonym', 'What is the antonym of assemble?', 'disperse', 'gather', 'collect', 'unite', 'To assemble means to gather together; to disperse means to scatter.'),
(143, 'attain', 'Antonym', 'What is the antonym of attain?', 'fail', 'achieve', 'reach', 'gain', 'To attain means to succeed in reaching something; to fail means not to achieve it.'),
(145, 'chaos', 'Antonym', 'What is the antonym of chaos?', 'order', 'conflict', 'turmoil', 'disruption', 'Chaos is disorder; order is structure and organization.'),
(146, 'comply', 'Antonym', 'What is the antonym of comply?', 'resist', 'obey', 'submit', 'follow', 'To comply means to follow rules; to resist means to oppose them.'),
(147, 'conclude', 'Antonym', 'What is the antonym of conclude?', 'begin', 'finish', 'end', 'finalize', 'To conclude means to end something; to begin means to start it.'),
(149, 'dense', 'Antonym', 'What is the antonym of dense?', 'sparse', 'thick', 'solid', 'compact', 'Dense means closely packed; sparse means spread out.'),
(150, 'despair', 'Antonym', 'What is the antonym of despair?', 'hope', 'grief', 'fear', 'sadness', 'Despair is a complete loss of hope; hope is a feeling of expectation or optimism.'),
(152, 'exclude', 'Antonym', 'What is the antonym of exclude?', 'include', 'omit', 'ignore', 'deny', 'Exclude means to leave out; include means to add in.'),
(154, 'genuine', 'Antonym', 'What is the antonym of genuine?', 'fake', 'true', 'authentic', 'honest', 'Genuine means real and authentic; fake means not real or deceptive.'),
(157, 'ideal', 'Antonym', 'What is the antonym of ideal?', 'flawed', 'perfect', 'optimal', 'desired', 'Ideal means perfect or best; flawed means having imperfections.'),
(158, 'intelligent', 'Antonym', 'What is the antonym of intelligent?', 'foolish', 'clever', 'bright', 'wise', 'Intelligent means smart; foolish means lacking sense or good judgment.'),
(159, 'liberation', 'Antonym', 'What is the antonym of liberation?', 'captivity', 'freedom', 'escape', 'relief', 'Liberation is gaining freedom; captivity is being held or confined.'),
(160, 'major', 'Antonym', 'What is the antonym of major?', 'minor', 'significant', 'primary', 'chief', 'Major means large or important; minor means small or less significant.'),
(161, 'mediate', 'Antonym', 'What is the antonym of mediate?', 'agitate', 'negotiate', 'resolve', 'settle', 'To mediate is to calm and help resolve conflict; to agitate is to stir up or worsen it.'),
(163, 'allocate', 'Antonym', 'What is the antonym of allocate?', 'withhold', 'assign', 'distribute', 'offer', 'To allocate means to assign; to withhold is to keep back.'),
(164, 'artificial', 'Antonym', 'What is the antonym of artificial?', 'natural', 'synthetic', 'plastic', 'fake', 'Artificial means man-made; natural means occurring in nature.'),
(165, 'authorize', 'Antonym', 'What is the antonym of authorize?', 'forbid', 'permit', 'approve', 'empower', 'To authorize is to allow or approve; to forbid is to prohibit.'),
(166, 'beneficial', 'Antonym', 'What is the antonym of beneficial?', 'harmful', 'useful', 'helpful', 'favorable', 'Beneficial means good for something; harmful means damaging.'),
(167, 'blunt', 'Antonym', 'What is the antonym of blunt?', 'sharp', 'dull', 'flat', 'thick', 'Blunt means not sharp or direct; sharp means pointed or keen.'),
(168, 'brief', 'Antonym', 'What is the antonym of brief?', 'lengthy', 'short', 'quick', 'rapid', 'Brief means short in duration; lengthy means long in duration.'),
(169, 'chaotic', 'Antonym', 'What is the antonym of chaotic?', 'orderly', 'wild', 'loud', 'erratic', 'Chaotic means disorganized; orderly means structured and organized.'),
(170, 'collapse', 'Antonym', 'What is the antonym of collapse?', 'rise', 'crumble', 'bend', 'decline', 'Collapse means to fall or fail suddenly; rise means to go up or succeed.'),
(171, 'conserve', 'Antonym', 'What is the antonym of conserve?', 'waste', 'save', 'preserve', 'store', 'To conserve means to protect or save; to waste means to use carelessly.'),
(172, 'defend', 'Antonym', 'What is the antonym of defend?', 'attack', 'protect', 'guard', 'secure', 'To defend means to protect; to attack means to harm or assault.'),
(173, 'demand', 'Antonym', 'What is the antonym of demand?', 'offer', 'request', 'ask', 'order', 'To demand means to insist; to offer is to give voluntarily.'),
(175, 'diligent', 'Antonym', 'What is the antonym of diligent?', 'lazy', 'hardworking', 'focused', 'disciplined', 'Diligent means hardworking and focused; lazy means unwilling to work.'),
(177, 'drastic', 'Antonym', 'What is the antonym of drastic?', 'mild', 'intense', 'harsh', 'sharp', 'Drastic means extreme or severe; mild means gentle or moderate.'),
(180, 'favorable', 'Antonym', 'What is the antonym of favorable?', 'hostile', 'positive', 'friendly', 'supportive', 'Favorable means supportive or beneficial; hostile means unfriendly or antagonistic.'),
(181, 'generate', 'Antonym', 'What is the antonym of generate?', 'destroy', 'produce', 'build', 'create', 'To generate means to create; to destroy means to eliminate.'),
(183, 'graceful', 'Antonym', 'What is the antonym of graceful?', 'clumsy', 'elegant', 'poised', 'smooth', 'Graceful means elegant in movement; clumsy means awkward or uncoordinated.'),
(184, 'harsh', 'Antonym', 'What is the antonym of harsh?', 'gentle', 'strict', 'firm', 'strong', 'Harsh means severe or rough; gentle means soft or mild.'),
(185, 'heighten', 'Antonym', 'What is the antonym of heighten?', 'diminish', 'raise', 'increase', 'elevate', 'To heighten means to intensify; to diminish means to reduce.'),
(186, 'honest', 'Antonym', 'What is the antonym of honest?', 'deceitful', 'truthful', 'modest', 'just', 'Honest means truthful; deceitful means misleading or lying.'),
(188, 'idealistic', 'Antonym', 'What is the antonym of idealistic?', 'realistic', 'dreamy', 'hopeful', 'inspired', 'Idealistic means guided by ideals; realistic means practical and grounded.'),
(189, 'ignite', 'Antonym', 'What is the antonym of ignite?', 'extinguish', 'spark', 'light', 'trigger', 'To ignite means to start a fire; to extinguish means to put it out.'),
(191, 'innocent', 'Antonym', 'What is the antonym of innocent?', 'guilty', 'naive', 'pure', 'honest', 'Innocent means not guilty; guilty means responsible for wrongdoing.'),
(194, 'maximum', 'Antonym', 'What is the antonym of maximum?', 'minimum', 'highest', 'limit', 'full', 'Maximum means the highest amount; minimum is the lowest.'),
(195, 'mild', 'Antonym', 'What is the antonym of mild?', 'severe', 'gentle', 'calm', 'quiet', 'Mild means gentle or not strong; severe means intense or harsh.'),
(196, 'modern', 'Antonym', 'What is the antonym of modern?', 'ancient', 'current', 'recent', 'new', 'Modern refers to the present; ancient refers to the distant past.'),
(197, 'motivated', 'Antonym', 'What is the antonym of motivated?', 'discouraged', 'inspired', 'active', 'focused', 'Motivated means driven or enthusiastic; discouraged means lacking motivation.'),
(198, 'mystery', 'Antonym', 'What is the antonym of mystery?', 'clarity', 'puzzle', 'secret', 'riddle', 'Mystery is something unknown; clarity is full understanding.'),
(199, 'neutral', 'Antonym', 'What is the antonym of neutral?', 'biased', 'unbiased', 'fair', 'indifferent', 'Neutral means not taking sides; biased means showing partiality.'),
(201, 'partial', 'Antonym', 'What is the antonym of partial?', 'complete', 'biased', 'uneven', 'specific', 'Partial means not whole or incomplete; complete means whole or finished.'),
(202, 'patient', 'Antonym', 'What is the antonym of patient?', 'impatient', 'tolerant', 'calm', 'peaceful', 'Patient means able to wait calmly; impatient means easily irritated by delay.'),
(205, 'present', 'Antonym', 'What is the antonym of present?', 'absent', 'here', 'available', 'visible', 'Present means being there; absent means not being there.'),
(206, 'protect', 'Antonym', 'What is the antonym of protect?', 'endanger', 'defend', 'guard', 'shelter', 'Protect means to keep safe; endanger means to put at risk.'),
(207, 'rare', 'Antonym', 'What is the antonym of rare?', 'common', 'unusual', 'odd', 'exclusive', 'Rare means not common; common means frequently occurring.'),
(208, 'reduce', 'Antonym', 'What is the antonym of reduce?', 'increase', 'cut', 'minimize', 'shrink', 'Reduce means to make smaller; increase means to make larger.'),
(209, 'reliable', 'Antonym', 'What is the antonym of reliable?', 'untrustworthy', 'dependable', 'loyal', 'steady', 'Reliable means trustworthy; untrustworthy means not dependable.'),
(210, 'repair', 'Antonym', 'What is the antonym of repair?', 'damage', 'fix', 'adjust', 'install', 'To repair means to fix; to damage means to break or harm.'),
(211, 'reveal', 'Antonym', 'What is the antonym of reveal?', 'conceal', 'expose', 'show', 'publish', 'To reveal means to show; to conceal means to hide.'),
(213, 'rise', 'Antonym', 'What is the antonym of rise?', 'fall', 'ascend', 'climb', 'elevate', 'To rise means to go upward; to fall means to go downward.'),
(214, 'rough', 'Antonym', 'What is the antonym of rough?', 'smooth', 'uneven', 'coarse', 'sharp', 'Rough means having an uneven surface; smooth means having an even surface.'),
(215, 'rural', 'Antonym', 'What is the antonym of rural?', 'urban', 'countryside', 'remote', 'farmland', 'Rural relates to the countryside; urban relates to the city.'),
(217, 'shallow', 'Antonym', 'What is the antonym of shallow?', 'deep', 'narrow', 'broad', 'short', 'Shallow means not deep; deep means extending far down.'),
(218, 'silent', 'Antonym', 'What is the antonym of silent?', 'noisy', 'quiet', 'still', 'calm', 'Silent means no sound; noisy means full of loud sound.'),
(219, 'simplify', 'Antonym', 'What is the antonym of simplify?', 'complicate', 'reduce', 'clarify', 'shorten', 'To simplify means to make easier; to complicate means to make more difficult.'),
(220, 'strengthen', 'Antonym', 'What is the antonym of strengthen?', 'weaken', 'build', 'support', 'reinforce', 'To strengthen means to make stronger; to weaken means to reduce strength.'),
(221, 'sorrow', 'Antonym', 'What is the antonym of sorrow?', 'joy', 'grief', 'guilt', 'pain', 'Sorrow is a feeling of deep sadness; joy is a feeling of great happiness.'),
(223, 'success', 'Antonym', 'What is the antonym of success?', 'failure', 'achievement', 'growth', 'progress', 'Success is achieving a goal; failure is not achieving it.'),
(224, 'suspend', 'Antonym', 'What is the antonym of suspend?', 'resume', 'stop', 'delay', 'halt', 'To suspend means to temporarily stop; to resume means to continue again.'),
(225, 'temporary', 'Antonym', 'What is the antonym of temporary?', 'permanent', 'brief', 'casual', 'occasional', 'Temporary means lasting a short time; permanent means lasting indefinitely.'),
(226, 'tension', 'Antonym', 'What is the antonym of tension?', 'relaxation', 'stress', 'tightness', 'strain', 'Tension is mental or emotional strain; relaxation is a state of rest.'),
(227, 'tolerant', 'Antonym', 'What is the antonym of tolerant?', 'intolerant', 'patient', 'open-minded', 'calm', 'Tolerant means accepting of differences; intolerant means rejecting them.'),
(228, 'triumph', 'Antonym', 'What is the antonym of triumph?', 'defeat', 'victory', 'celebration', 'conquest', 'Triumph is a great win or victory; defeat is a loss.'),
(230, 'value', 'Antonym', 'What is the antonym of value?', 'worthlessness', 'price', 'importance', 'cost', 'Value means importance or worth; worthlessness means having no value.'),
(235, 'wide', 'Antonym', 'What is the antonym of wide?', 'narrow', 'broad', 'vast', 'large', 'Wide means broad in extent; narrow means limited in width.'),
(236, 'wisdom', 'Antonym', 'What is the antonym of wisdom?', 'foolishness', 'intelligence', 'understanding', 'logic', 'Wisdom is good judgment; foolishness is poor or silly judgment.'),
(237, 'active', 'Antonym', 'What is the antonym of active?', 'inactive', 'energetic', 'busy', 'fit', 'Active means full of movement or energy; inactive means not moving or participating.'),
(238, 'accept', 'Antonym', 'What is the antonym of accept?', 'decline', 'agree', 'approve', 'welcome', 'To accept means to agree or receive; to decline means to refuse.'),
(242, 'allow', 'Antonym', 'What is the antonym of allow?', 'forbid', 'permit', 'accept', 'approve', 'To allow means to give permission; to forbid means to refuse permission.'),
(244, 'awake', 'Antonym', 'What is the antonym of awake?', 'asleep', 'alert', 'aware', 'vigilant', 'Awake means not sleeping; asleep means in a state of sleep.'),
(246, 'bravery', 'Antonym', 'What is the antonym of bravery?', 'cowardice', 'valor', 'courage', 'honor', 'Bravery means courage in danger; cowardice means lack of courage.'),
(247, 'combine', 'Antonym', 'What is the antonym of combine?', 'separate', 'merge', 'join', 'blend', 'To combine means to bring things together; to separate means to take them apart.'),
(248, 'complicated', 'Antonym', 'What is the antonym of complicated?', 'simple', 'confusing', 'detailed', 'elaborate', 'Complicated means difficult to understand; simple means easy to understand.'),
(250, 'danger', 'Antonym', 'What is the antonym of danger?', 'safety', 'risk', 'peril', 'harm', 'Danger means a possibility of harm; safety means protection from harm.'),
(252, 'distant', 'Antonym', 'What is the antonym of distant?', 'near', 'far', 'remote', 'wide', 'Distant means far away; near means close by.'),
(253, 'divide', 'Antonym', 'What is the antonym of divide?', 'unite', 'split', 'separate', 'classify', 'To divide is to split; to unite is to bring together.'),
(254, 'employer', 'Antonym', 'What is the antonym of employer?', 'employee', 'boss', 'leader', 'manager', 'An employer gives jobs; an employee works under them.'),
(255, 'entrance', 'Antonym', 'What is the antonym of entrance?', 'exit', 'gate', 'arrival', 'doorway', 'Entrance is a way in; exit is a way out.'),
(257, 'export', 'Antonym', 'What is the antonym of export?', 'import', 'deliver', 'ship', 'move', 'To export is to send out; to import is to bring in.'),
(258, 'float', 'Antonym', 'What is the antonym of float?', 'sink', 'rise', 'hover', 'sail', 'Float means to stay above water; sink means to go below the surface.'),
(260, 'future', 'Antonym', 'What is the antonym of future?', 'past', 'next', 'ahead', 'later', 'Future refers to what is to come; past refers to what has already happened.'),
(261, 'gain', 'Antonym', 'What is the antonym of gain?', 'lose', 'collect', 'earn', 'secure', 'Gain means to acquire; lose means to no longer have something.'),
(263, 'gentle', 'Antonym', 'What is the antonym of gentle?', 'harsh', 'soft', 'tender', 'light', 'Gentle means mild or soft; harsh means severe or rough.'),
(264, 'grant', 'Antonym', 'What is the antonym of grant?', 'refuse', 'give', 'offer', 'accept', 'To grant is to give or allow; to refuse is to deny.'),
(265, 'guilty', 'Antonym', 'What is the antonym of guilty?', 'innocent', 'ashamed', 'convicted', 'culpable', 'Guilty means responsible for wrongdoing; innocent means not guilty.'),
(267, 'honor', 'Antonym', 'What is the antonym of honor?', 'disgrace', 'respect', 'credit', 'award', 'Honor means respect or esteem; disgrace means loss of respect.'),
(271, 'join', 'Antonym', 'What is the antonym of join?', 'separate', 'combine', 'connect', 'link', 'To join is to bring together; to separate is to set apart.'),
(273, 'known', 'Antonym', 'What is the antonym of known?', 'unknown', 'familiar', 'seen', 'identified', 'Known means recognized or familiar; unknown means unfamiliar.'),
(274, 'lead', 'Antonym', 'What is the antonym of lead?', 'follow', 'guide', 'manage', 'control', 'To lead means to guide; to follow means to go after.'),
(276, 'light', 'Antonym', 'What is the antonym of light?', 'dark', 'bright', 'sunny', 'white', 'Light is brightness; dark is the absence of light.'),
(280, 'merge', 'Antonym', 'What is the antonym of merge?', 'split', 'combine', 'join', 'absorb', 'To merge is to join together; to split is to divide apart.'),
(282, 'misery', 'Antonym', 'What is the antonym of misery?', 'happiness', 'pain', 'grief', 'fear', 'Misery means great suffering; happiness means joy and contentment.'),
(283, 'multiply', 'Antonym', 'What is the antonym of multiply?', 'divide', 'increase', 'expand', 'grow', 'To multiply means to increase; to divide means to separate or reduce.'),
(284, 'near', 'Antonym', 'What is the antonym of near?', 'far', 'close', 'next', 'nearby', 'Near means close by; far means distant.'),
(285, 'open', 'Antonym', 'What is the antonym of open?', 'closed', 'wide', 'clear', 'free', 'Open means not shut; closed means not open.'),
(286, 'optimism', 'Antonym', 'What is the antonym of optimism?', 'pessimism', 'hope', 'belief', 'faith', 'Optimism is expecting the best; pessimism is expecting the worst.'),
(288, 'peace', 'Antonym', 'What is the antonym of peace?', 'war', 'calm', 'harmony', 'order', 'Peace is a state of tranquility; war is violent conflict.'),
(290, 'plenty', 'Antonym', 'What is the antonym of plenty?', 'scarcity', 'abundance', 'supply', 'wealth', 'Plenty means a large quantity; scarcity means not enough.'),
(292, 'positive', 'Antonym', 'What is the antonym of positive?', 'negative', 'hopeful', 'cheerful', 'sure', 'Positive means affirming or good; negative means denying or bad.'),
(293, 'poverty', 'Antonym', 'What is the antonym of poverty?', 'wealth', 'misery', 'shortage', 'hunger', 'Poverty means being very poor; wealth means having plenty of money or resources.'),
(295, 'private', 'Antonym', 'What is the antonym of private?', 'public', 'secret', 'personal', 'hidden', 'Private means restricted or personal; public means open to all.'),
(297, 'refuse', 'Antonym', 'What is the antonym of refuse?', 'accept', 'deny', 'reject', 'decline', 'To refuse means to reject; to accept means to agree or receive.'),
(298, 'remember', 'Antonym', 'What is the antonym of remember?', 'forget', 'recall', 'remind', 'recognize', 'To remember means to recall something; to forget means to not recall.'),
(304, 'safe', 'Antonym', 'What is the antonym of safe?', 'dangerous', 'secure', 'calm', 'guarded', 'Safe means free from harm; dangerous means full of risk or harm.'),
(305, 'scatter', 'Antonym', 'What is the antonym of scatter?', 'gather', 'spread', 'drop', 'disperse', 'Scatter means to spread out; gather means to bring together.'),
(307, 'shrink', 'Antonym', 'What is the antonym of shrink?', 'grow', 'contract', 'tighten', 'squeeze', 'To shrink means to become smaller; to grow means to increase in size.'),
(308, 'simple', 'Antonym', 'What is the antonym of simple?', 'complex', 'easy', 'plain', 'clear', 'Simple means uncomplicated; complex means made of many parts.'),
(309, 'sink', 'Antonym', 'What is the antonym of sink?', 'float', 'drop', 'plunge', 'settle', 'Sink means to go below the surface; float means to stay on the surface.'),
(310, 'slim', 'Antonym', 'What is the antonym of slim?', 'fat', 'thin', 'skinny', 'lean', 'Slim means thin or slender; fat means overweight or heavy.'),
(312, 'speed', 'Antonym', 'What is the antonym of speed?', 'slowness', 'velocity', 'rush', 'pace', 'Speed means fast movement; slowness means moving slowly.'),
(317, 'thick', 'Antonym', 'What is the antonym of thick?', 'thin', 'dense', 'solid', 'heavy', 'Thick means having a large distance between sides; thin means narrow or slender.'),
(318, 'tough', 'Antonym', 'What is the antonym of tough?', 'fragile', 'strong', 'hard', 'firm', 'Tough means durable or strong; fragile means easily broken or damaged.'),
(319, 'true', 'Antonym', 'What is the antonym of true?', 'false', 'honest', 'loyal', 'accurate', 'True means correct or real; false means incorrect or not real.'),
(324, 'ascend', 'Antonym', 'What is the antonym of ascend?', 'descend', 'rise', 'lift', 'climb', 'Ascend means to go up; descend means to go down.'),
(325, 'beginning', 'Antonym', 'What is the antonym of beginning?', 'end', 'opening', 'origin', 'start', 'Beginning refers to the start; end refers to the finish.'),
(326, 'bitter', 'Antonym', 'What is the antonym of bitter?', 'sweet', 'sour', 'spicy', 'salty', 'Bitter describes a sharp, unpleasant taste; sweet is the opposite.'),
(327, 'build', 'Antonym', 'What is the antonym of build?', 'destroy', 'construct', 'assemble', 'develop', 'To build means to create or construct; destroy means to ruin or dismantle.'),
(328, 'calm', 'Antonym', 'What is the antonym of calm?', 'agitated', 'peaceful', 'relaxed', 'quiet', 'Calm means relaxed or still; agitated means disturbed or restless.'),
(329, 'cheap', 'Antonym', 'What is the antonym of cheap?', 'expensive', 'affordable', 'simple', 'low', 'Cheap means low in cost; expensive means high in cost.'),
(330, 'clean', 'Antonym', 'What is the antonym of clean?', 'dirty', 'pure', 'neat', 'tidy', 'Clean means free from dirt; dirty means covered in dirt or mess.'),
(332, 'dark', 'Antonym', 'What is the antonym of dark?', 'light', 'shadowy', 'black', 'dim', 'Dark refers to absence of light; light is brightness.'),
(333, 'day', 'Antonym', 'What is the antonym of day?', 'night', 'sunrise', 'dawn', 'noon', 'Day is the light part of the day; night is the dark part.'),
(334, 'early', 'Antonym', 'What is the antonym of early?', 'late', 'prompt', 'on-time', 'quick', 'Early means before the expected time; late means after the expected time.'),
(335, 'easy', 'Antonym', 'What is the antonym of easy?', 'difficult', 'simple', 'light', 'quick', 'Easy means not hard; difficult means hard to do.'),
(337, 'fail', 'Antonym', 'What is the antonym of fail?', 'succeed', 'lose', 'miss', 'fall', 'Fail means not achieve; succeed means accomplish a goal.'),
(341, 'give', 'Antonym', 'What is the antonym of give?', 'take', 'offer', 'share', 'grant', 'To give is to offer something to someone; to take is to receive or seize.'),
(342, 'happy', 'Antonym', 'What is the antonym of happy?', 'sad', 'joyful', 'cheerful', 'lively', 'Happy means feeling joy; sad means feeling sorrow.'),
(343, 'hard', 'Antonym', 'What is the antonym of hard?', 'soft', 'firm', 'solid', 'dense', 'Hard means firm or solid; soft means yielding or gentle.'),
(344, 'high', 'Antonym', 'What is the antonym of high?', 'low', 'tall', 'wide', 'big', 'High means elevated; low means not elevated or near the ground.'),
(345, 'hot', 'Antonym', 'What is the antonym of hot?', 'cold', 'warm', 'boiling', 'spicy', 'Hot refers to high temperature; cold refers to low temperature.'),
(349, 'kind', 'Antonym', 'What is the antonym of kind?', 'cruel', 'nice', 'gentle', 'friendly', 'Kind means considerate; cruel means causing pain or suffering.'),
(350, 'large', 'Antonym', 'What is the antonym of large?', 'small', 'big', 'wide', 'huge', 'Large means big in size; small means little in size.'),
(351, 'laugh', 'Antonym', 'What is the antonym of laugh?', 'cry', 'smile', 'chuckle', 'grin', 'To laugh is to express joy; to cry is to express sadness.'),
(353, 'live', 'Antonym', 'What is the antonym of live?', 'die', 'survive', 'breathe', 'thrive', 'To live means to be alive; to die means to cease living.'),
(354, 'long', 'Antonym', 'What is the antonym of long?', 'short', 'tall', 'deep', 'wide', 'Long means extended in length; short means limited in length.'),
(355, 'loud', 'Antonym', 'What is the antonym of loud?', 'quiet', 'noisy', 'sharp', 'clear', 'Loud means high in volume; quiet means low in volume or silent.'),
(356, 'love', 'Antonym', 'What is the antonym of love?', 'hate', 'like', 'care', 'adore', 'Love is strong affection; hate is intense dislike.'),
(359, 'natural', 'Antonym', 'What is the antonym of natural?', 'artificial', 'organic', 'real', 'pure', 'Natural means occurring in nature; artificial means man-made.'),
(360, 'new', 'Antonym', 'What is the antonym of new?', 'old', 'fresh', 'recent', 'modern', 'New means recently created; old means existing for a long time.'),
(361, 'night', 'Antonym', 'What is the antonym of night?', 'day', 'evening', 'dusk', 'midnight', 'Night is the dark period of a day; day is the light period.'),
(362, 'noisy', 'Antonym', 'What is the antonym of noisy?', 'quiet', 'loud', 'rowdy', 'sharp', 'Noisy means full of sound; quiet means low or no sound.'),
(363, 'old', 'Antonym', 'What is the antonym of old?', 'young', 'aged', 'ancient', 'past', 'Old means having lived long; young means early in life.'),
(365, 'ordinary', 'Antonym', 'What is the antonym of ordinary?', 'extraordinary', 'common', 'typical', 'basic', 'Ordinary means usual; extraordinary means exceptional.'),
(366, 'pain', 'Antonym', 'What is the antonym of pain?', 'pleasure', 'hurt', 'suffering', 'sting', 'Pain is discomfort; pleasure is enjoyable feeling.'),
(368, 'peaceful', 'Antonym', 'What is the antonym of peaceful?', 'violent', 'quiet', 'calm', 'gentle', 'Peaceful means calm or without conflict; violent means involving conflict or harm.'),
(371, 'pretty', 'Antonym', 'What is the antonym of pretty?', 'ugly', 'lovely', 'beautiful', 'cute', 'Pretty means attractive; ugly means unpleasant in appearance.'),
(373, 'profit', 'Antonym', 'What is the antonym of profit?', 'loss', 'gain', 'earning', 'bonus', 'Profit is financial gain; loss is financial reduction.'),
(374, 'push', 'Antonym', 'What is the antonym of push?', 'pull', 'shove', 'press', 'move', 'Push means to move away by force; pull means to draw closer.'),
(375, 'question', 'Antonym', 'What is the antonym of question?', 'answer', 'ask', 'query', 'reply', 'A question is an inquiry; an answer is a response.'),
(376, 'raise', 'Antonym', 'What is the antonym of raise?', 'lower', 'lift', 'increase', 'elevate', 'To raise means to move up; to lower means to move down.'),
(377, 'real', 'Antonym', 'What is the antonym of real?', 'fake', 'true', 'genuine', 'authentic', 'Real means genuine; fake means not genuine.'),
(378, 'rich', 'Antonym', 'What is the antonym of rich?', 'poor', 'wealthy', 'loaded', 'affluent', 'Rich means having a lot of money; poor means having very little.'),
(379, 'right', 'Antonym', 'What is the antonym of right?', 'wrong', 'just', 'fair', 'honest', 'Right means correct; wrong means incorrect.'),
(382, 'rude', 'Antonym', 'What is the antonym of rude?', 'polite', 'harsh', 'mean', 'abrupt', 'Rude means disrespectful; polite means courteous and respectful.'),
(383, 'sad', 'Antonym', 'What is the antonym of sad?', 'happy', 'quiet', 'tired', 'calm', 'Sad means feeling sorrow; happy means feeling joy.'),
(385, 'scream', 'Antonym', 'What is the antonym of scream?', 'whisper', 'shout', 'cry', 'yell', 'To scream is to make a loud noise; to whisper is to speak very softly.'),
(386, 'secure', 'Antonym', 'What is the antonym of secure?', 'insecure', 'safe', 'tight', 'firm', 'Secure means safe and protected; insecure means unsafe or uncertain.'),
(387, 'sell', 'Antonym', 'What is the antonym of sell?', 'buy', 'offer', 'give', 'lend', 'To sell is to give something in exchange for money; to buy is to purchase something.'),
(388, 'sharp', 'Antonym', 'What is the antonym of sharp?', 'dull', 'pointed', 'keen', 'crisp', 'Sharp means having a fine edge; dull means lacking sharpness.'),
(389, 'short', 'Antonym', 'What is the antonym of short?', 'long', 'tiny', 'thin', 'narrow', 'Short means having little length; long means extended length.'),
(390, 'shout', 'Antonym', 'What is the antonym of shout?', 'murmur', 'yell', 'cheer', 'call', 'To shout is to speak loudly; to murmur is to speak softly.'),
(393, 'slow', 'Antonym', 'What is the antonym of slow?', 'fast', 'late', 'gradual', 'steady', 'Slow means not quick; fast means moving quickly.'),
(394, 'small', 'Antonym', 'What is the antonym of small?', 'large', 'tiny', 'narrow', 'low', 'Small means little in size or amount; large means big.'),
(395, 'soft', 'Antonym', 'What is the antonym of soft?', 'hard', 'smooth', 'gentle', 'mild', 'Soft means easy to press or gentle; hard means firm or tough.'),
(396, 'solid', 'Antonym', 'What is the antonym of solid?', 'liquid', 'firm', 'strong', 'dense', 'Solid is a state of matter; liquid is another physical state.'),
(397, 'start', 'Antonym', 'What is the antonym of start?', 'stop', 'begin', 'go', 'open', 'Start means to begin; stop means to end or halt.'),
(398, 'stay', 'Antonym', 'What is the antonym of stay?', 'leave', 'remain', 'wait', 'rest', 'Stay means to remain in place; leave means to go away.'),
(399, 'strong', 'Antonym', 'What is the antonym of strong?', 'weak', 'solid', 'firm', 'tough', 'Strong means having power or strength; weak means lacking strength.'),
(401, 'subtract', 'Antonym', 'What is the antonym of subtract?', 'add', 'deduct', 'decrease', 'remove', 'To subtract is to take away; to add is to increase by combining.'),
(402, 'tall', 'Antonym', 'What is the antonym of tall?', 'short', 'big', 'wide', 'narrow', 'Tall means having great height; short means having little height.'),
(404, 'thin', 'Antonym', 'What is the antonym of thin?', 'thick', 'slim', 'light', 'lean', 'Thin means narrow or not wide; thick means broad or dense.'),
(405, 'together', 'Antonym', 'What is the antonym of together?', 'apart', 'united', 'grouped', 'gathered', 'Together means in a group or close; apart means separated.'),
(406, 'top', 'Antonym', 'What is the antonym of top?', 'bottom', 'peak', 'tip', 'height', 'Top refers to the highest point; bottom is the lowest part.'),
(410, 'wake', 'Antonym', 'What is the antonym of wake?', 'sleep', 'rise', 'get up', 'move', 'To wake means to stop sleeping; to sleep means to be at rest.'),
(411, 'warm', 'Antonym', 'What is the antonym of warm?', 'cool', 'hot', 'mild', 'gentle', 'Warm means slightly hot; cool means mildly cold.'),
(412, 'waste', 'Antonym', 'What is the antonym of waste?', 'save', 'spend', 'throw', 'use', 'To waste is to use carelessly; to save is to preserve or conserve.'),
(413, 'weak', 'Antonym', 'What is the antonym of weak?', 'strong', 'soft', 'gentle', 'mild', 'Weak means lacking strength; strong means having great power.'),
(414, 'win', 'Antonym', 'What is the antonym of win?', 'lose', 'gain', 'succeed', 'earn', 'To win means to succeed or gain victory; to lose means to fail or be defeated.'),
(415, 'wise', 'Antonym', 'What is the antonym of wise?', 'foolish', 'smart', 'learned', 'clever', 'Wise means having good judgment; foolish means lacking sense or wisdom.'),
(416, 'work', 'Antonym', 'What is the antonym of work?', 'rest', 'job', 'effort', 'labor', 'Work is effort or activity; rest is relaxation or inaction.'),
(417, 'young', 'Antonym', 'What is the antonym of young?', 'old', 'teen', 'new', 'fresh', 'Young means early in life; old means having lived a long time.'),
(419, 'above', 'Antonym', 'What is the antonym of above?', 'below', 'over', 'upon', 'near', 'Above refers to a higher position; below refers to a lower one.'),
(420, 'arrive', 'Antonym', 'What is the antonym of arrive?', 'depart', 'reach', 'come', 'approach', 'To arrive is to reach a place; to depart is to leave it.'),
(421, 'attack', 'Antonym', 'What is the antonym of attack?', 'defend', 'hit', 'charge', 'invade', 'To attack is to act aggressively; to defend is to protect.'),
(422, 'beautiful', 'Antonym', 'What is the antonym of beautiful?', 'ugly', 'lovely', 'pretty', 'attractive', 'Beautiful means visually pleasing; ugly means unpleasant in appearance.'),
(423, 'begin', 'Antonym', 'What is the antonym of begin?', 'end', 'start', 'open', 'launch', 'To begin is to start; to end is to finish.'),
(424, 'borrow', 'Antonym', 'What is the antonym of borrow?', 'lend', 'take', 'share', 'hold', 'To borrow is to receive something temporarily; to lend is to give it temporarily.');

INSERT INTO `1_antonym` (`id`, `word`, `type`, `question`, `correct_answer`, `wrong_answer1`, `wrong_answer2`, `wrong_answer3`, `explanation`) VALUES
(425, 'brave', 'Antonym', 'What is the antonym of brave?', 'cowardly', 'strong', 'bold', 'fearless', 'Brave means courageous; cowardly means lacking courage.'),
(426, 'buy', 'Antonym', 'What is the antonym of buy?', 'sell', 'shop', 'give', 'order', 'To buy is to acquire by paying; to sell is to give in exchange for payment.'),
(428, 'close', 'Antonym', 'What is the antonym of close?', 'open', 'shut', 'tight', 'lock', 'Close means to shut; open means to make accessible.'),
(431, 'deep', 'Antonym', 'What is the antonym of deep?', 'shallow', 'wide', 'dark', 'sharp', 'Deep refers to great depth; shallow refers to limited depth.'),
(432, 'enemy', 'Antonym', 'What is the antonym of enemy?', 'friend', 'rival', 'stranger', 'foe', 'An enemy is someone hostile; a friend is someone supportive.'),
(433, 'enter', 'Antonym', 'What is the antonym of enter?', 'exit', 'approach', 'go', 'proceed', 'To enter is to go in; to exit is to go out.'),
(434, 'evening', 'Antonym', 'What is the antonym of evening?', 'morning', 'night', 'afternoon', 'midnight', 'Evening is the latter part of the day; morning is the start.'),
(436, 'fall', 'Antonym', 'What is the antonym of fall?', 'rise', 'drop', 'descend', 'collapse', 'To fall is to go downward; to rise is to go upward.'),
(437, 'fast', 'Antonym', 'What is the antonym of fast?', 'slow', 'quick', 'rapid', 'swift', 'Fast means quick; slow means not quick.'),
(438, 'forget', 'Antonym', 'What is the antonym of forget?', 'remember', 'ignore', 'skip', 'lose', 'To forget is to not recall; to remember is to recall.'),
(439, 'full', 'Antonym', 'What is the antonym of full?', 'empty', 'complete', 'packed', 'whole', 'Full means containing as much as possible; empty means having nothing inside.'),
(443, 'heavy', 'Antonym', 'What is the antonym of heavy?', 'light', 'dense', 'deep', 'massive', 'Heavy means great in weight; light means having little weight.'),
(445, 'inside', 'Antonym', 'What is the antonym of inside?', 'outside', 'inner', 'interior', 'deep', 'Inside means within; outside means beyond or external.'),
(446, 'joy', 'Antonym', 'What is the antonym of joy?', 'sorrow', 'happiness', 'pleasure', 'fun', 'Joy is a feeling of great happiness; sorrow is deep sadness.'),
(447, 'last', 'Antonym', 'What is the antonym of last?', 'first', 'final', 'latest', 'ending', 'Last means coming after all others; first means coming before all others.'),
(448, 'late', 'Antonym', 'What is the antonym of late?', 'early', 'delayed', 'tardy', 'slow', 'Late means after the expected time; early means before it.'),
(450, 'less', 'Antonym', 'What is the antonym of less?', 'more', 'some', 'little', 'few', 'Less means a smaller amount; more means a greater amount.'),
(453, 'many', 'Antonym', 'What is the antonym of many?', 'few', 'some', 'lots', 'several', 'Many means a large number; few means a small number.'),
(456, 'narrow', 'Antonym', 'What is the antonym of narrow?', 'wide', 'tight', 'small', 'thin', 'Narrow means not wide; wide means having a large width.'),
(458, 'past', 'Antonym', 'What is the antonym of past?', 'future', 'present', 'history', 'before', 'Past is time gone by; future is time yet to come.'),
(462, 'receive', 'Antonym', 'What is the antonym of receive?', 'give', 'collect', 'accept', 'gather', 'To receive is to get something; to give is to provide something to others.'),
(467, 'same', 'Antonym', 'What is the antonym of same?', 'different', 'alike', 'similar', 'identical', 'Same means identical or alike; different means not the same.'),
(469, 'save', 'Antonym', 'What is the antonym of save?', 'spend', 'store', 'keep', 'preserve', 'Save means to keep or store; spend means to use or consume.'),
(473, 'show', 'Antonym', 'What is the antonym of show?', 'hide', 'display', 'present', 'reveal', 'To show is to make visible; to hide is to conceal.'),
(483, 'ugly', 'Antonym', 'What is the antonym of ugly?', 'beautiful', 'rough', 'plain', 'odd', 'Ugly means unpleasant to look at; beautiful means visually attractive.'),
(484, 'under', 'Antonym', 'What is the antonym of under?', 'over', 'below', 'beneath', 'inside', 'Under means beneath something; over means above it.'),
(485, 'up', 'Antonym', 'What is the antonym of up?', 'down', 'above', 'top', 'rise', 'Up means toward a higher position; down means toward a lower one.'),
(490, 'wet', 'Antonym', 'What is the antonym of wet?', 'dry', 'moist', 'damp', 'soaked', 'Wet means covered in liquid; dry means free from moisture.'),
(501, 'careful', 'Antonym', 'What is the antonym of careful?', 'careless', 'attentive', 'wise', 'exact', 'Careful means cautious and thorough; careless means negligent.'),
(502, 'catch', 'Antonym', 'What is the antonym of catch?', 'miss', 'grab', 'stop', 'drop', 'To catch means to seize; to miss means to fail to seize.'),
(506, 'cold', 'Antonym', 'What is the antonym of cold?', 'hot', 'cool', 'mild', 'calm', 'Cold means having low temperature; hot means high temperature.'),
(507, 'come', 'Antonym', 'What is the antonym of come?', 'go', 'arrive', 'walk', 'reach', 'To come is to approach; to go is to move away.'),
(509, 'connect', 'Antonym', 'What is the antonym of connect?', 'disconnect', 'attach', 'combine', 'tie', 'To connect is to link; to disconnect is to sever the link.'),
(510, 'correct', 'Antonym', 'What is the antonym of correct?', 'wrong', 'right', 'exact', 'true', 'Correct means accurate; wrong means inaccurate.'),
(513, 'depart', 'Antonym', 'What is the antonym of depart?', 'arrive', 'leave', 'travel', 'exit', 'To depart is to go away; to arrive is to reach a place.'),
(514, 'descend', 'Antonym', 'What is the antonym of descend?', 'ascend', 'fall', 'lower', 'drop', 'To descend is to move downward; to ascend is to move upward.'),
(516, 'dry', 'Antonym', 'What is the antonym of dry?', 'wet', 'arid', 'moist', 'damp', 'Dry means free of moisture; wet means covered with water.'),
(518, 'empty', 'Antonym', 'What is the antonym of empty?', 'full', 'blank', 'clear', 'bare', 'Empty means without contents; full means containing all it can.'),
(520, 'everywhere', 'Antonym', 'What is the antonym of everywhere?', 'nowhere', 'anywhere', 'somewhere', 'nearby', 'Everywhere means in all places; nowhere means in no place.'),
(524, 'far', 'Antonym', 'What is the antonym of far?', 'near', 'wide', 'away', 'remote', 'Far means distant; near means close by.'),
(525, 'fat', 'Antonym', 'What is the antonym of fat?', 'thin', 'wide', 'large', 'big', 'Fat means having excess body weight; thin means slim or lean.'),
(526, 'few', 'Antonym', 'What is the antonym of few?', 'many', 'some', 'less', 'several', 'Few means a small number; many means a large number.'),
(528, 'follow', 'Antonym', 'What is the antonym of follow?', 'lead', 'obey', 'chase', 'track', 'To follow means to come after; to lead means to go in front.'),
(529, 'friend', 'Antonym', 'What is the antonym of friend?', 'enemy', 'companion', 'buddy', 'ally', 'A friend is someone you like and trust; an enemy is someone opposed to you.'),
(532, 'gather', 'Antonym', 'What is the antonym of gather?', 'scatter', 'collect', 'combine', 'assemble', 'Gather means to bring together; scatter means to spread apart.'),
(533, 'go', 'Antonym', 'What is the antonym of go?', 'stay', 'leave', 'run', 'move', 'Go means to move away; stay means to remain in place.'),
(534, 'good', 'Antonym', 'What is the antonym of good?', 'bad', 'kind', 'nice', 'great', 'Good means morally right or desirable; bad means morally wrong or undesirable.'),
(539, 'hate', 'Antonym', 'What is the antonym of hate?', 'love', 'dislike', 'anger', 'fear', 'Hate is intense dislike; love is deep affection.'),
(541, 'hide', 'Antonym', 'What is the antonym of hide?', 'show', 'cover', 'block', 'shadow', 'To hide means to keep out of sight; to show means to make visible.'),
(544, 'hungry', 'Antonym', 'What is the antonym of hungry?', 'full', 'empty', 'tired', 'fed', 'Hungry means needing food; full means satisfied or no longer hungry.'),
(549, 'learn', 'Antonym', 'What is the antonym of learn?', 'forget', 'study', 'know', 'practice', 'To learn is to acquire knowledge; to forget is to lose it.'),
(550, 'leave', 'Antonym', 'What is the antonym of leave?', 'stay', 'go', 'exit', 'move', 'To leave means to depart; to stay means to remain.'),
(551, 'lend', 'Antonym', 'What is the antonym of lend?', 'borrow', 'give', 'grant', 'offer', 'To lend is to give temporarily; to borrow is to receive temporarily.'),
(559, 'melt', 'Antonym', 'What is the antonym of melt?', 'freeze', 'boil', 'steam', 'cool', 'To melt is to turn to liquid; to freeze is to become solid.'),
(560, 'messy', 'Antonym', 'What is the antonym of messy?', 'neat', 'dirty', 'sloppy', 'loose', 'Messy means disorganized; neat means tidy and orderly.'),
(561, 'minor', 'Antonym', 'What is the antonym of minor?', 'major', 'small', 'tiny', 'short', 'Minor means less important or smaller; major means more important or larger.'),
(562, 'miserable', 'Antonym', 'What is the antonym of miserable?', 'cheerful', 'sad', 'lonely', 'dull', 'Miserable means very unhappy; cheerful means visibly happy.'),
(564, 'more', 'Antonym', 'What is the antonym of more?', 'less', 'extra', 'many', 'bigger', 'More means a greater amount; less means a smaller amount.'),
(567, 'neat', 'Antonym', 'What is the antonym of neat?', 'messy', 'clean', 'clear', 'nice', 'Neat means tidy or orderly; messy means untidy or disorganized.'),
(570, 'north', 'Antonym', 'What is the antonym of north?', 'south', 'east', 'west', 'up', 'North is one direction on a compass; south is its opposite.'),
(571, 'nothing', 'Antonym', 'What is the antonym of nothing?', 'everything', 'something', 'none', 'empty', 'Nothing means absence of anything; everything means all that exists.'),
(572, 'off', 'Antonym', 'What is the antonym of off?', 'on', 'down', 'stop', 'shut', 'Off means not operating; on means operating or active.'),
(576, 'out', 'Antonym', 'What is the antonym of out?', 'in', 'off', 'far', 'away', 'Out means outside or away; in means inside.'),
(577, 'over', 'Antonym', 'What is the antonym of over?', 'under', 'above', 'top', 'up', 'Over means above or on top; under means beneath.'),
(579, 'part', 'Antonym', 'What is the antonym of part?', 'whole', 'bit', 'piece', 'side', 'Part means a portion of something; whole means the entire thing.'),
(582, 'pleasant', 'Antonym', 'What is the antonym of pleasant?', 'unpleasant', 'nice', 'charming', 'delightful', 'Pleasant means enjoyable or pleasing; unpleasant means not enjoyable.'),
(583, 'plural', 'Antonym', 'What is the antonym of plural?', 'singular', 'dual', 'group', 'many', 'Plural refers to more than one; singular means only one.'),
(584, 'poor', 'Antonym', 'What is the antonym of poor?', 'rich', 'broke', 'cheap', 'simple', 'Poor means lacking money; rich means having wealth.'),
(586, 'possible', 'Antonym', 'What is the antonym of possible?', 'impossible', 'available', 'doable', 'achievable', 'Possible means able to happen; impossible means not able to happen.'),
(589, 'quiet', 'Antonym', 'What is the antonym of quiet?', 'loud', 'silent', 'still', 'soft', 'Quiet means having little noise; loud means having a lot of noise.'),
(604, 'sick', 'Antonym', 'What is the antonym of sick?', 'healthy', 'weak', 'injured', 'tired', 'Sick means ill or unwell; healthy means in good physical condition.'),
(611, 'some', 'Antonym', 'What is the antonym of some?', 'none', 'few', 'all', 'many', 'Some means a portion; none means nothing at all.'),
(612, 'south', 'Antonym', 'What is the antonym of south?', 'north', 'east', 'west', 'bottom', 'South is one compass direction; north is its opposite.'),
(616, 'sunrise', 'Antonym', 'What is the antonym of sunrise?', 'sunset', 'daybreak', 'morning', 'noon', 'Sunrise is the sun appearing; sunset is the sun disappearing.'),
(617, 'sweet', 'Antonym', 'What is the antonym of sweet?', 'bitter', 'salty', 'soft', 'warm', 'Sweet describes sugary taste; bitter is sharp and unpleasant.'),
(618, 'take', 'Antonym', 'What is the antonym of take?', 'give', 'grab', 'steal', 'receive', 'To take is to acquire; to give is to offer to someone else.'),
(631, 'white', 'Antonym', 'What is the antonym of white?', 'black', 'pale', 'bright', 'gray', 'White is the lightest color; black is the darkest.'),
(640, 'asleep', 'Antonym', 'What is the antonym of asleep?', 'awake', 'sleepy', 'still', 'silent', 'Asleep means in a state of sleep; awake means not sleeping.'),
(641, 'attach', 'Antonym', 'What is the antonym of attach?', 'detach', 'connect', 'bind', 'stick', 'Attach means to fasten or join; detach means to separate.'),
(643, 'before', 'Antonym', 'What is the antonym of before?', 'after', 'during', 'ahead', 'soon', 'Before means earlier in time; after means later.'),
(648, 'bright', 'Antonym', 'What is the antonym of bright?', 'dim', 'shiny', 'clear', 'vivid', 'Bright means full of light; dim means lacking brightness.'),
(659, 'dangerous', 'Antonym', 'What is the antonym of dangerous?', 'safe', 'risky', 'deadly', 'bold', 'Dangerous means likely to cause harm; safe means not harmful.'),
(664, 'difficult', 'Antonym', 'What is the antonym of difficult?', 'easy', 'hard', 'tricky', 'tough', 'Difficult means hard to do; easy means not hard.'),
(665, 'dim', 'Antonym', 'What is the antonym of dim?', 'bright', 'dull', 'dark', 'low', 'Dim means lacking light; bright means full of light.'),
(666, 'dirty', 'Antonym', 'What is the antonym of dirty?', 'clean', 'messy', 'dusty', 'muddy', 'Dirty means not clean; clean means free from dirt.'),
(667, 'disagree', 'Antonym', 'What is the antonym of disagree?', 'agree', 'argue', 'deny', 'resist', 'To disagree is to have a different opinion; to agree is to share the same view.'),
(669, 'down', 'Antonym', 'What is the antonym of down?', 'up', 'below', 'under', 'low', 'Down means toward a lower place; up means toward a higher place.'),
(672, 'east', 'Antonym', 'What is the antonym of east?', 'west', 'north', 'south', 'top', 'East is one cardinal direction; west is the opposite.'),
(675, 'even', 'Antonym', 'What is the antonym of even?', 'odd', 'equal', 'fair', 'flat', 'Even means divisible by two; odd means not divisible by two.'),
(678, 'false', 'Antonym', 'What is the antonym of false?', 'true', 'wrong', 'fake', 'deceptive', 'False means incorrect; true means correct.'),
(682, 'fill', 'Antonym', 'What is the antonym of fill?', 'empty', 'load', 'pour', 'pack', 'To fill is to make full; to empty is to remove contents.'),
(683, 'finish', 'Antonym', 'What is the antonym of finish?', 'start', 'end', 'close', 'pause', 'Finish means to complete something; start means to begin it.'),
(686, 'foolish', 'Antonym', 'What is the antonym of foolish?', 'wise', 'funny', 'silly', 'naive', 'Foolish means lacking good sense; wise means having sound judgment.'),
(688, 'freeze', 'Antonym', 'What is the antonym of freeze?', 'melt', 'cool', 'crack', 'solidify', 'Freeze means become solid; melt means become liquid.'),
(690, 'front', 'Antonym', 'What is the antonym of front?', 'back', 'top', 'start', 'head', 'Front is the forward part; back is the rear part.'),
(694, 'giant', 'Antonym', 'What is the antonym of giant?', 'tiny', 'huge', 'tall', 'massive', 'Giant means very large; tiny means very small.'),
(697, 'great', 'Antonym', 'What is the antonym of great?', 'terrible', 'amazing', 'huge', 'strong', 'Great means excellent; terrible means very bad.'),
(701, 'have', 'Antonym', 'What is the antonym of have?', 'lack', 'own', 'get', 'hold', 'Have means to possess; lack means to be without.'),
(702, 'health', 'Antonym', 'What is the antonym of health?', 'illness', 'fitness', 'strength', 'energy', 'Health means a state of well-being; illness is a condition of poor health.'),
(704, 'help', 'Antonym', 'What is the antonym of help?', 'harm', 'assist', 'save', 'support', 'To help is to aid or support; to harm is to injure or damage.'),
(705, 'here', 'Antonym', 'What is the antonym of here?', 'there', 'near', 'close', 'inside', 'Here refers to the current location; there refers to another location.'),
(707, 'hire', 'Antonym', 'What is the antonym of hire?', 'fire', 'employ', 'recruit', 'assign', 'To hire means to employ someone; to fire means to dismiss from a job.'),
(708, 'hold', 'Antonym', 'What is the antonym of hold?', 'release', 'grip', 'grasp', 'keep', 'To hold is to grasp or keep; to release is to let go.'),
(715, 'junior', 'Antonym', 'What is the antonym of junior?', 'senior', 'younger', 'minor', 'beginner', 'Junior means lower in rank or younger; senior means higher or older.'),
(717, 'knowledge', 'Antonym', 'What is the antonym of knowledge?', 'ignorance', 'learning', 'education', 'insight', 'Knowledge means information or understanding; ignorance means lack of it.'),
(726, 'like', 'Antonym', 'What is the antonym of like?', 'dislike', 'love', 'enjoy', 'prefer', 'To like means to enjoy or favor; to dislike means to not enjoy.'),
(729, 'lose', 'Antonym', 'What is the antonym of lose?', 'win', 'fail', 'miss', 'drop', 'To lose is to be defeated; to win is to be successful.'),
(734, 'master', 'Antonym', 'What is the antonym of master?', 'servant', 'teacher', 'leader', 'expert', 'A master is one in control; a servant is one who obeys.'),
(739, 'miss', 'Antonym', 'What is the antonym of miss?', 'catch', 'lose', 'pass', 'avoid', 'To miss is to fail to get; to catch is to successfully receive or reach.'),
(748, 'none', 'Antonym', 'What is the antonym of none?', 'all', 'few', 'some', 'several', 'None means not any; all means every one.'),
(753, 'on', 'Antonym', 'What is the antonym of on?', 'off', 'open', 'start', 'go', 'On means active or operating; off means not operating.'),
(755, 'opposite', 'Antonym', 'What is the antonym of opposite?', 'same', 'reverse', 'different', 'facing', 'Opposite means completely different; same means identical or equal.'),
(767, 'quick', 'Antonym', 'What is the antonym of quick?', 'slow', 'fast', 'swift', 'sudden', 'Quick means fast; slow means not fast.'),
(774, 'rest', 'Antonym', 'What is the antonym of rest?', 'work', 'sleep', 'pause', 'wait', 'Rest is a state of relaxation; work is a state of activity.'),
(806, 'teach', 'Antonym', 'What is the antonym of teach?', 'learn', 'train', 'show', 'guide', 'To teach is to give knowledge; to learn is to receive knowledge.'),
(808, 'throw', 'Antonym', 'What is the antonym of throw?', 'catch', 'drop', 'pass', 'hit', 'To throw is to send through the air; to catch is to receive.'),
(809, 'tight', 'Antonym', 'What is the antonym of tight?', 'loose', 'firm', 'strong', 'small', 'Tight means firmly fixed; loose means not firmly attached.'),
(827, 'bless', 'Antonym', 'What is the antonym of bless?', 'curse', 'praise', 'thank', 'wish', 'To bless means to confer good; to curse means to wish harm.'),
(830, 'clear', 'Antonym', 'What is the antonym of clear?', 'cloudy', 'bright', 'open', 'wide', 'Clear means free from obstruction; cloudy means not clear.'),
(832, 'cool', 'Antonym', 'What is the antonym of cool?', 'warm', 'cold', 'mild', 'chill', 'Cool means moderately cold; warm means slightly hot.'),
(840, 'find', 'Antonym', 'What is the antonym of find?', 'lose', 'search', 'seek', 'drop', 'To find means to discover; to lose means to no longer have or locate.'),
(841, 'first', 'Antonym', 'What is the antonym of first?', 'last', 'early', 'lead', 'top', 'First means coming before all others; last means coming after all others.'),
(861, 'huge', 'Antonym', 'What is the antonym of huge?', 'tiny', 'big', 'large', 'vast', 'Huge means very large in size; tiny means very small.'),
(864, 'interesting', 'Antonym', 'What is the antonym of interesting?', 'boring', 'exciting', 'fascinating', 'engaging', 'Interesting means capturing attention or curiosity; boring means dull or uninteresting.'),
(873, 'move', 'Antonym', 'What is the antonym of move?', 'stay', 'shift', 'go', 'walk', 'Move means to change position; stay means to remain in place.'),
(893, 'think', 'Antonym', 'What is the antonym of think?', 'ignore', 'consider', 'reflect', 'decide', 'To think is to use the mind for processing; to ignore is to disregard.'),
(903, 'ancient', 'Antonym', 'What is the antonym of ancient?', 'modern', 'old', 'historic', 'classic', 'Ancient means very old or from a long time ago; modern means current or recent.'),
(904, 'appear', 'Antonym', 'What is the antonym of appear?', 'disappear', 'show', 'emerge', 'arrive', 'To appear means to become visible; to disappear means to cease to be seen.'),
(911, 'broad', 'Antonym', 'What is the antonym of broad?', 'narrow', 'wide', 'large', 'deep', 'Broad means wide or expansive; narrow means limited in width.'),
(915, 'common', 'Antonym', 'What is the antonym of common?', 'rare', 'unusual', 'frequent', 'ordinary', 'Common means usual or frequent; rare means uncommon or infrequent.'),
(921, 'end', 'Antonym', 'What is the antonym of end?', 'begin', 'start', 'finish', 'open', 'End means to finish something; begin means to start it.'),
(925, 'essential', 'Antonym', 'What is the antonym of essential?', 'nonessential', 'important', 'necessary', 'vital', 'Essential means crucial or necessary; nonessential means not necessary.'),
(931, 'fix', 'Antonym', 'What is the antonym of fix?', 'break', 'repair', 'correct', 'mend', 'To fix means to repair something; to break means to damage or make unusable.'),
(934, 'fun', 'Antonym', 'What is the antonym of fun?', 'boring', 'enjoyable', 'exciting', 'interesting', 'Fun means enjoyable; boring means dull and uninteresting.'),
(940, 'outside', 'Antonym', 'What is the antonym of outside?', 'inside', 'external', 'outdoor', 'beyond', 'Outside refers to being beyond a boundary; inside refers to being within it.'),
(942, 'own', 'Antonym', 'What is the antonym of own?', 'borrow', 'keep', 'receive', 'acquire', 'To own means to possess something; to borrow means to take something temporarily.'),
(1048, 'hope', 'Antonym', 'What is the antonym of hope?', 'despair', 'faith', 'wish', 'believe', 'Hope means expecting good things; despair means expecting bad things.'),
(1056, 'low', 'Antonym', 'What is the antonym of low?', 'high', 'deep', 'tall', 'high', 'Low means being close to the ground; high means elevated.');

