INSERT INTO `verbal` 
(`category`, `type`, `word`, `question`, `image`, `correct_answer`, `wrong_answer1`, `wrong_answer2`, `wrong_answer3`, `explanation`) 
VALUES
('Word Meaning and Usage', 'Contextual Meaning', 'Serene', 'Choose the meaning of the word "Serene" based on the context: "The lake was calm and serene, with no disturbance in sight."', '', 'Calm and peaceful', 'Chaotic', 'Energetic', 'Turbulent', 'The word "Serene" refers to being calm and peaceful, often describing an environment or atmosphere free of disturbance.'),
('Word Meaning and Usage', 'Contextual Meaning', 'Exuberant', 'Choose the meaning of the word "Exuberant" based on the context: "She greeted everyone with an exuberant smile, full of joy and enthusiasm."', '', 'Full of energy and excitement', 'Tired', 'Sad', 'Indifferent', 'The word "Exuberant" describes a high level of energy, excitement, or enthusiasm.'),
('Word Meaning and Usage', 'Contextual Meaning', 'Meticulous', 'Choose the meaning of the word "Meticulous" based on the context: "He was meticulous in organizing the files, ensuring everything was in its proper place."', '', 'Showing great attention to detail', 'Careless', 'Impatient', 'Disorganized', 'The word "Meticulous" refers to being extremely careful and paying great attention to detail in tasks or actions.'),
('Word Meaning and Usage', 'Contextual Meaning', 'Adversity', 'Choose the meaning of the word "Adversity" based on the context: "They faced adversity during their journey, overcoming many obstacles along the way."', '', 'Difficulties or misfortune', 'Success', 'Luck', 'Ease', 'The word "Adversity" refers to difficulties or challenges faced, often leading to hardship or suffering.'),
('Word Meaning and Usage', 'Contextual Meaning', 'Enervated', 'Choose the meaning of the word "Enervated" based on the context: "The long journey left him enervated, with no strength to move."', '', 'Exhausted or drained of energy', 'Energetic', 'Healthy', 'Motivated', 'The word "Enervated" means feeling drained of energy, weak, or physically exhausted.'),
('Word Meaning and Usage', 'Contextual Meaning', 'Altruistic', 'Choose the meaning of the word "Altruistic" based on the context: "Her altruistic nature led her to donate all her savings to charity."', '', 'Showing selfless concern for others', 'Selfish', 'Apathetic', 'Greedy', 'The word "Altruistic" refers to being concerned with the welfare of others, often demonstrated through selfless actions.'),
('Word Meaning and Usage', 'Contextual Meaning', 'Cacophony', 'Choose the meaning of the word "Cacophony" based on the context: "The cacophony of horns and sirens filled the streets during rush hour."', '', 'A harsh, discordant mixture of sounds', 'Harmony', 'Melody', 'Silence', 'The word "Cacophony" refers to a loud, unpleasant mixture of noises, often jarring or chaotic.'),
('Word Meaning and Usage', 'Contextual Meaning', 'Benevolent', 'Choose the meaning of the word "Benevolent" based on the context: "The benevolent king donated large sums of money to the poor."', '', 'Kind and charitable', 'Cruel', 'Apathetic', 'Selfish', 'The word "Benevolent" describes someone who is kind-hearted and generous, often with a focus on helping others.'),
('Word Meaning and Usage', 'Contextual Meaning', 'Voracious', 'Choose the meaning of the word "Voracious" based on the context: "He had a voracious appetite, devouring everything on his plate."', '', 'Having a huge appetite or desire', 'Picky', 'Full', 'Indifferent', 'The word "Voracious" refers to having a great hunger or desire, often used to describe an intense craving for food or knowledge.'),
('Word Meaning and Usage', 'Contextual Meaning', 'Disparage', 'Choose the meaning of the word "Disparage" based on the context: "He disparaged his colleague’s idea, calling it foolish and unoriginal."', '', 'To speak about someone in a negative or disrespectful way', 'To praise', 'To ignore', 'To discuss politely', 'The word "Disparage" means to criticize or belittle someone or something, often unfairly or harshly.'),
('Word Meaning and Usage', 'Contextual Meaning', 'Prolific', 'Choose the meaning of the word "Prolific" based on the context: "The artist was prolific, creating dozens of paintings each year."', '', 'Producing a large amount of work', 'Lazy', 'Inefficient', 'Unproductive', 'The word "Prolific" describes someone who produces a lot of work or creates in abundance.'),
('Word Meaning and Usage', 'Contextual Meaning', 'Trepidation', 'Choose the meaning of the word "Trepidation" based on the context: "He approached the stage with trepidation, nervous about speaking in front of the crowd."', '', 'Fear or anxiety', 'Excitement', 'Confidence', 'Indifference', 'The word "Trepidation" refers to a feeling of fear or anxiety about something uncertain or daunting.'),
('Word Meaning and Usage', 'Contextual Meaning', 'Apathetic', 'Choose the meaning of the word "Apathetic" based on the context: "She remained apathetic during the meeting, showing no interest or emotion."', '', 'Lacking interest or emotion', 'Excited', 'Passionate', 'Engaged', 'The word "Apathetic" means showing a lack of interest, enthusiasm, or emotion toward something.'),
('Word Meaning and Usage', 'Contextual Meaning', 'Sagacious', 'Choose the meaning of the word "Sagacious" based on the context: "The sagacious leader made wise decisions during difficult times."', '', 'Wise and insightful', 'Naive', 'Foolish', 'Indecisive', 'The word "Sagacious" refers to being wise, insightful, and showing good judgment, especially in difficult situations.'),
('Word Meaning and Usage', 'Contextual Meaning', 'Ephemeral', 'Choose the meaning of the word "Ephemeral" based on the context: "Their happiness was ephemeral, fading quickly after the event was over."', '', 'Short-lived or fleeting', 'Enduring', 'Constant', 'Timeless', 'The word "Ephemeral" describes something that lasts for a very short time or is fleeting in nature.'),
('Word Meaning and Usage', 'Contextual Meaning', 'Garrulous', 'Choose the meaning of the word "Garrulous" based on the context: "He was garrulous, talking for hours about trivial matters."', '', 'Excessively talkative', 'Reserved', 'Silent', 'Shy', 'The word "Garrulous" refers to someone who talks excessively, often about trivial matters.'),
('Word Meaning and Usage', 'Contextual Meaning', 'Inevitable', 'Choose the meaning of the word "Inevitable" based on the context: "The collapse of the company seemed inevitable after years of mismanagement."', '', 'Certain to happen', 'Avoidable', 'Unlikely', 'Unexpected', 'The word "Inevitable" refers to something that is certain to happen and cannot be avoided.'),
('Word Meaning and Usage', 'Contextual Meaning', 'Obfuscate', 'Choose the meaning of the word "Obfuscate" based on the context: "The politician tried to obfuscate the truth by giving vague answers."', '', 'To confuse or make unclear', 'Clarify', 'Simplify', 'Explain', 'The word "Obfuscate" means to make something unclear or difficult to understand, often intentionally.'),
('Word Meaning and Usage', 'Contextual Meaning', 'Capricious', 'Choose the meaning of the word "Capricious" based on the context: "Her capricious behavior made it difficult to predict what she would do next."', '', 'Impulsive and unpredictable', 'Steady', 'Rational', 'Consistent', 'The word "Capricious" describes behavior that is unpredictable, often driven by sudden or impulsive changes in mood or decision.'),
('Word Meaning and Usage', 'Contextual Meaning', 'Lethargic', 'Choose the meaning of the word "Lethargic" based on the context: "He felt lethargic after staying up all night studying."', '', 'Sluggish and lacking energy', 'Energetic', 'Alert', 'Active', 'The word "Lethargic" refers to being sluggish, drowsy, or lacking the energy to perform usual activities.'),
('Word Meaning and Usage', 'Contextual Meaning', 'Obsequious', 'Choose the meaning of the word "Obsequious" based on the context: "His obsequious behavior around his boss made everyone uncomfortable."', '', 'Excessively eager to please', 'Independent', 'Proud', 'Defiant', 'The word "Obsequious" refers to being overly eager to please or serve others, often in a way that is insincere or servile.'),
('Word Meaning and Usage', 'Contextual Meaning', 'Prodigious', 'Choose the meaning of the word "Prodigious" based on the context: "The team made a prodigious effort to complete the project on time."', '', 'Extraordinary in size or effort', 'Small', 'Insignificant', 'Average', 'The word "Prodigious" refers to something extraordinary, large, or remarkable, often in terms of effort, size, or achievement.'),
('Word Meaning and Usage', 'Contextual Meaning', 'Frivolous', 'Choose the meaning of the word "Frivolous" based on the context: "The judge dismissed the case, deeming it frivolous and without merit."', '', 'Not serious or important', 'Serious', 'Important', 'Significant', 'The word "Frivolous" refers to something that is not serious, lacking importance or relevance.'),
('Word Meaning and Usage', 'Contextual Meaning', 'Equanimity', 'Choose the meaning of the word "Equanimity" based on the context: "She handled the stressful situation with remarkable equanimity."', '', 'Mental calmness and composure', 'Panic', 'Anxiety', 'Confusion', 'The word "Equanimity" refers to maintaining mental calmness and composure, especially in difficult or stressful situations.');

