

INSERT INTO `verbal` (`category`, `type`, `word`, `question`, `image`, `correct_answer`, `wrong_answer1`, `wrong_answer2`, `wrong_answer3`, `explanation`, `created_at`) VALUES
('Word Meaning and Usage', 'Antonym', 'Abundant', 'Choose the antonym of the word \"Abundant\".', NULL, 'Scarce', 'Plentiful', 'Ample', 'Bountiful', 'The antonym of \"Abundant\" is \"Scarce\", meaning lacking or insufficient.', '2025-06-30 06:07:10'),
('Word Meaning and Usage', 'Antonym', 'Ancient', 'Choose the antonym of the word \"Ancient\".', NULL, 'Modern', 'Old', 'Historic', 'Antique', 'The antonym of \"Ancient\" is \"Modern\", which refers to something recent or current.', '2025-06-30 06:07:10'),
( 'Word Meaning and Usage', 'Antonym', 'Generous', 'Choose the antonym of the word \"Generous\".', NULL, 'Stingy', 'Kind', 'Helpful', 'Liberal', 'The antonym of \"Generous\" is \"Stingy\", meaning unwilling to give or spend.', '2025-06-30 06:07:10'),
( 'Word Meaning and Usage', 'Antonym', 'Transparent', 'Choose the antonym of the word \"Transparent\".', NULL, 'Opaque', 'Clear', 'Lucid', 'Visible', 'The antonym of \"Transparent\" is \"Opaque\", which means not allowing light to pass through.', '2025-06-30 06:07:10'),
( 'Word Meaning and Usage', 'Antonym', 'Brave', 'Choose the antonym of the word \"Brave\".', NULL, 'Cowardly', 'Fearless', 'Bold', 'Valiant', 'The antonym of \"Brave\" is \"Cowardly\", meaning lacking courage or easily scared.', '2025-06-30 06:07:10'),
( 'Word Meaning and Usage', 'Causality or Result Identification', 'Pollution', 'What is a likely result of increased pollution in urban areas?', NULL, 'Health problems', 'Economic boom', 'Technological advancement', 'Population growth', 'Pollution often leads to health problems like asthma, allergies, and other respiratory issues.', '2025-06-30 06:07:27'),
( 'Word Meaning and Usage', 'Causality or Result Identification', 'Deforestation', 'What is a direct result of deforestation?', NULL, 'Loss of biodiversity', 'Improved air quality', 'Increased rainfall', 'Soil enrichment', 'Deforestation leads to habitat loss, which causes a decrease in biodiversity.', '2025-06-30 06:07:27'),
( 'Word Meaning and Usage', 'Causality or Result Identification', 'Lack of sleep', 'What is a common consequence of lack of sleep?', NULL, 'Reduced concentration', 'Increased energy', 'Better memory', 'Enhanced immunity', 'Lack of sleep often causes reduced concentration and cognitive impairment.', '2025-06-30 06:07:27'),
( 'Word Meaning and Usage', 'Causality or Result Identification', 'Global warming', 'Which of the following is a result of global warming?', NULL, 'Rising sea levels', 'Falling sea levels', 'Stable temperatures', 'Less extreme weather', 'Global warming causes ice to melt and sea levels to rise.', '2025-06-30 06:07:27'),
( 'Word Meaning and Usage', 'Causality or Result Identification', 'Smoking', 'What is a potential result of long-term smoking?', NULL, 'Lung cancer', 'Weight loss', 'Improved stamina', 'Clear skin', 'Long-term smoking significantly increases the risk of developing lung cancer.', '2025-06-30 06:07:27');