
INSERT INTO analytical (category, type, question, chart_data, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation, created_at) VALUES 
('Data Interpretation', 'bar', 'Which branch experienced alternating monthly customer turnout?', '{"labels": ["Jan", "Feb", "Mar", "Apr", "May"], "datasets": [{"label": "Branch A", "data": [200, 150, 200, 150, 200], "backgroundColor": "#AB47BC"}, {"label": "Branch B", "data": [180, 190, 200, 210, 220], "backgroundColor": "#FFA726"}]}', 'Branch A', 'Branch B', 'Branch C', 'Branch D', 'Branch A alternates exactly between 200 and 150 across the months.', NOW()),
('Data Interpretation', 'bar', 'Which machine output pattern alternated perfectly during testing?', '{"labels": ["Test 1", "Test 2", "Test 3", "Test 4", "Test 5"], "datasets": [{"label": "Machine X", "data": [100, 120, 100, 120, 100], "backgroundColor": "#26A69A"}, {"label": "Machine Y", "data": [95, 97, 99, 101, 103], "backgroundColor": "#EF5350"}]}', 'Machine X', 'Machine Y', 'Machine Z', 'Machine W', 'Machine X alternated consistently between 100 and 120 output.', NOW()),
('Data Interpretation', 'bar', 'Who showed a perfect alternating weekly attendance pattern?', '{"labels": ["Week 1", "Week 2", "Week 3", "Week 4", "Week 5"], "datasets": [{"label": "Ella", "data": [5, 3, 5, 3, 5], "backgroundColor": "#7E57C2"}, {"label": "Liam", "data": [4, 4, 4, 4, 4], "backgroundColor": "#66BB6A"}]}', 'Ella', 'Liam', 'Mila', 'Noah', 'Ella’s attendance alternated perfectly between 5 and 3 days per week.', NOW()),
('Data Interpretation', 'bar', 'Which product’s sales followed an up-down pattern over the months?', '{"labels": ["Jan", "Feb", "Mar", "Apr", "May"], "datasets": [{"label": "Product Alpha", "data": [300, 350, 300, 350, 300], "backgroundColor": "#FFCA28"}, {"label": "Product Beta", "data": [310, 320, 330, 340, 350], "backgroundColor": "#42A5F5"}]}', 'Product Alpha', 'Product Beta', 'Product Gamma', 'Product Delta', 'Product Alpha’s sales alternated between 300 and 350 units.', NOW()),
('Data Interpretation', 'bar', 'Which participant showed a back-and-forth performance trend?', '{"labels": ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5"], "datasets": [{"label": "Tina", "data": [60, 70, 60, 70, 60], "backgroundColor": "#29B6F6"}, {"label": "George", "data": [55, 60, 65, 70, 75], "backgroundColor": "#9CCC65"}]}', 'Tina', 'George', 'Alan', 'Mira', 'Tina’s performance alternated between 60 and 70 points daily.', NOW());

INSERT INTO analytical (category, type, question, chart_data, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation, created_at) VALUES 
('Data Interpretation', 'bar', 'Which employee’s weekly output followed a strict alternating pattern?', '{"labels": ["Week 1", "Week 2", "Week 3", "Week 4", "Week 5"], "datasets": [{"label": "Jordan", "data": [80, 100, 80, 100, 80], "backgroundColor": "#8E24AA"}, {"label": "Casey", "data": [85, 87, 89, 91, 93], "backgroundColor": "#43A047"}]}', 'Jordan', 'Casey', 'Riley', 'Morgan', 'Jordan’s output alternated precisely between 80 and 100 each week.', NOW()),
('Data Interpretation', 'bar', 'Which department had an alternating expense pattern throughout the quarter?', '{"labels": ["Jan", "Feb", "Mar", "Apr", "May"], "datasets": [{"label": "Dept X", "data": [400, 500, 400, 500, 400], "backgroundColor": "#039BE5"}, {"label": "Dept Y", "data": [450, 460, 470, 480, 490], "backgroundColor": "#FDD835"}]}', 'Dept X', 'Dept Y', 'Dept Z', 'Dept A', 'Dept X alternated between 400 and 500 in a consistent pattern.', NOW()),
('Data Interpretation', 'bar', 'Which student alternated their test scores every session?', '{"labels": ["Test 1", "Test 2", "Test 3", "Test 4", "Test 5"], "datasets": [{"label": "Sam", "data": [75, 85, 75, 85, 75], "backgroundColor": "#26A69A"}, {"label": "Alex", "data": [78, 79, 80, 81, 82], "backgroundColor": "#FF7043"}]}', 'Sam', 'Alex', 'Jamie', 'Taylor', 'Sam scored alternately 75 and 85 in a repeating pattern.', NOW()),
('Data Interpretation', 'bar', 'Which vendor alternated between high and low deliveries each month?', '{"labels": ["Jan", "Feb", "Mar", "Apr", "May"], "datasets": [{"label": "Vendor A", "data": [1000, 800, 1000, 800, 1000], "backgroundColor": "#7E57C2"}, {"label": "Vendor B", "data": [950, 960, 970, 980, 990], "backgroundColor": "#66BB6A"}]}', 'Vendor A', 'Vendor B', 'Vendor C', 'Vendor D', 'Vendor A followed a perfect up-down delivery cycle.', NOW()),
('Data Interpretation', 'bar', 'Which athlete’s performance alternated regularly during the tournament?', '{"labels": ["Round 1", "Round 2", "Round 3", "Round 4", "Round 5"], "datasets": [{"label": "Neil", "data": [22, 28, 22, 28, 22], "backgroundColor": "#5C6BC0"}, {"label": "Ryan", "data": [20, 21, 22, 23, 24], "backgroundColor": "#FFB74D"}]}', 'Neil', 'Ryan', 'Carl', 'Victor', 'Neil’s scores alternated consistently between 22 and 28.', NOW());

INSERT INTO analytical (category, type, question, chart_data, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation, created_at) VALUES 
('Data Interpretation', 'bar', 'Which intern alternated perfectly between two productivity levels?', '{"labels": ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5"], "datasets": [{"label": "Ivy", "data": [60, 80, 60, 80, 60], "backgroundColor": "#EC407A"}, {"label": "Owen", "data": [65, 70, 75, 80, 85], "backgroundColor": "#42A5F5"}]}', 'Ivy', 'Owen', 'Lena', 'Mark', 'Ivy’s productivity alternated between 60 and 80 throughout the week.', NOW()),
('Data Interpretation', 'bar', 'Which call center showed an alternating volume of customer calls?', '{"labels": ["Mon", "Tue", "Wed", "Thu", "Fri"], "datasets": [{"label": "Center East", "data": [120, 90, 120, 90, 120], "backgroundColor": "#AB47BC"}, {"label": "Center West", "data": [100, 110, 120, 130, 140], "backgroundColor": "#66BB6A"}]}', 'Center East', 'Center West', 'Center North', 'Center South', 'Center East alternated exactly between 120 and 90 calls.', NOW()),
('Data Interpretation', 'bar', 'Which marketing campaign had a back-and-forth trend in reach?', '{"labels": ["Week 1", "Week 2", "Week 3", "Week 4", "Week 5"], "datasets": [{"label": "Campaign Z", "data": [5000, 7000, 5000, 7000, 5000], "backgroundColor": "#FFCA28"}, {"label": "Campaign Y", "data": [5200, 5300, 5400, 5500, 5600], "backgroundColor": "#26C6DA"}]}', 'Campaign Z', 'Campaign Y', 'Campaign X', 'Campaign Q', 'Campaign Z switched between 5000 and 7000 reach every week.', NOW()),
('Data Interpretation', 'bar', 'Which delivery route showed alternating fuel usage each trip?', '{"labels": ["Trip 1", "Trip 2", "Trip 3", "Trip 4", "Trip 5"], "datasets": [{"label": "Route 5", "data": [30, 40, 30, 40, 30], "backgroundColor": "#29B6F6"}, {"label": "Route 8", "data": [32, 34, 36, 38, 40], "backgroundColor": "#EF5350"}]}', 'Route 5', 'Route 8', 'Route 3', 'Route 6', 'Route 5 alternated fuel usage perfectly between 30 and 40 liters.', NOW()),
('Data Interpretation', 'bar', 'Which student alternated high and low grades during finals?', '{"labels": ["Subject 1", "Subject 2", "Subject 3", "Subject 4", "Subject 5"], "datasets": [{"label": "Karen", "data": [88, 95, 88, 95, 88], "backgroundColor": "#8D6E63"}, {"label": "Jason", "data": [90, 91, 92, 93, 94], "backgroundColor": "#4DB6AC"}]}', 'Karen', 'Jason', 'Ella', 'Lucas', 'Karen alternated grades between 88 and 95 in each subject.', NOW());

INSERT INTO analytical (category, type, question, chart_data, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation, created_at) VALUES 
('Data Interpretation', 'bar', 'Which sales representative had an alternating performance pattern?', '{"labels": ["Week 1", "Week 2", "Week 3", "Week 4", "Week 5"], "datasets": [{"label": "Derek", "data": [150, 180, 150, 180, 150], "backgroundColor": "#F06292"}, {"label": "Angela", "data": [160, 165, 170, 175, 180], "backgroundColor": "#4FC3F7"}]}', 'Derek', 'Angela', 'Mason', 'Claire', 'Derek’s sales alternated exactly between 150 and 180.', NOW()),
('Data Interpretation', 'bar', 'Which server’s response time alternated over test cycles?', '{"labels": ["Cycle 1", "Cycle 2", "Cycle 3", "Cycle 4", "Cycle 5"], "datasets": [{"label": "Server A", "data": [200, 250, 200, 250, 200], "backgroundColor": "#9575CD"}, {"label": "Server B", "data": [210, 215, 220, 225, 230], "backgroundColor": "#AED581"}]}', 'Server A', 'Server B', 'Server C', 'Server D', 'Server A alternated between 200 and 250 ms response time.', NOW()),
('Data Interpretation', 'bar', 'Which warehouse alternated its shipment volume each month?', '{"labels": ["Jan", "Feb", "Mar", "Apr", "May"], "datasets": [{"label": "Warehouse 1", "data": [700, 900, 700, 900, 700], "backgroundColor": "#7986CB"}, {"label": "Warehouse 2", "data": [800, 820, 840, 860, 880], "backgroundColor": "#FFD54F"}]}', 'Warehouse 1', 'Warehouse 2', 'Warehouse 3', 'Warehouse 4', 'Warehouse 1 alternated shipment volume between 700 and 900 units.', NOW()),
('Data Interpretation', 'bar', 'Which power station alternated its output during peak hours?', '{"labels": ["Hour 1", "Hour 2", "Hour 3", "Hour 4", "Hour 5"], "datasets": [{"label": "Station Green", "data": [400, 500, 400, 500, 400], "backgroundColor": "#4DB6AC"}, {"label": "Station Blue", "data": [450, 460, 470, 480, 490], "backgroundColor": "#FF8A65"}]}', 'Station Green', 'Station Blue', 'Station Red', 'Station White', 'Station Green alternated between 400 and 500 kW consistently.', NOW()),
('Data Interpretation', 'bar', 'Which online course saw an alternating enrollment pattern?', '{"labels": ["Session 1", "Session 2", "Session 3", "Session 4", "Session 5"], "datasets": [{"label": "Course A", "data": [60, 80, 60, 80, 60], "backgroundColor": "#BA68C8"}, {"label": "Course B", "data": [65, 70, 75, 80, 85], "backgroundColor": "#81C784"}]}', 'Course A', 'Course B', 'Course C', 'Course D', 'Course A enrollment alternated between 60 and 80 students.', NOW());

INSERT INTO analytical (category, type, question, chart_data, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation, created_at) VALUES 
('Data Interpretation', 'bar', 'Which analyst submitted reports in an alternating pattern over weeks?', '{"labels": ["Week 1", "Week 2", "Week 3", "Week 4", "Week 5"], "datasets": [{"label": "Ethan", "data": [10, 15, 10, 15, 10], "backgroundColor": "#4FC3F7"}, {"label": "Mia", "data": [12, 13, 14, 15, 16], "backgroundColor": "#FFB74D"}]}', 'Ethan', 'Mia', 'Liam', 'Zoe', 'Ethan alternated between 10 and 15 reports weekly.', NOW()),
('Data Interpretation', 'bar', 'Which blogger had a consistent alternate-posting frequency?', '{"labels": ["Mon", "Tue", "Wed", "Thu", "Fri"], "datasets": [{"label": "Bella", "data": [2, 4, 2, 4, 2], "backgroundColor": "#7986CB"}, {"label": "Leo", "data": [3, 3, 3, 3, 3], "backgroundColor": "#81C784"}]}', 'Bella', 'Leo', 'Ava', 'Eli', 'Bella alternated her post count between 2 and 4 each day.', NOW()),
('Data Interpretation', 'bar', 'Which city alternated its rainfall over the week?', '{"labels": ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5"], "datasets": [{"label": "City A", "data": [5, 10, 5, 10, 5], "backgroundColor": "#BA68C8"}, {"label": "City B", "data": [6, 7, 8, 9, 10], "backgroundColor": "#FF8A65"}]}', 'City A', 'City B', 'City C', 'City D', 'City A alternated rainfall values between 5mm and 10mm.', NOW()),
('Data Interpretation', 'bar', 'Which freelancer alternated weekly hours strictly?', '{"labels": ["Week 1", "Week 2", "Week 3", "Week 4", "Week 5"], "datasets": [{"label": "Nora", "data": [20, 30, 20, 30, 20], "backgroundColor": "#4DD0E1"}, {"label": "Tom", "data": [25, 26, 27, 28, 29], "backgroundColor": "#DCE775"}]}', 'Nora', 'Tom', 'Ella', 'Ray', 'Nora’s hours alternated between 20 and 30 each week.', NOW()),
('Data Interpretation', 'bar', 'Which store alternated its revenue pattern every other month?', '{"labels": ["Jan", "Feb", "Mar", "Apr", "May"], "datasets": [{"label": "Store 1", "data": [1000, 1500, 1000, 1500, 1000], "backgroundColor": "#CE93D8"}, {"label": "Store 2", "data": [1100, 1200, 1300, 1400, 1500], "backgroundColor": "#A5D6A7"}]}', 'Store 1', 'Store 2', 'Store 3', 'Store 4', 'Store 1’s revenue alternated between 1000 and 1500 monthly.', NOW());

INSERT INTO analytical (category, type, question, chart_data, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation, created_at) VALUES 
('Data Interpretation', 'bar', 'Which content creator alternated the number of videos uploaded each week?', '{"labels": ["Week 1", "Week 2", "Week 3", "Week 4", "Week 5"], "datasets": [{"label": "Aiden", "data": [3, 5, 3, 5, 3], "backgroundColor": "#4DD0E1"}, {"label": "Olivia", "data": [4, 4, 4, 4, 4], "backgroundColor": "#FF8A65"}]}', 'Aiden', 'Olivia', 'Logan', 'Zara', 'Aiden alternated perfectly between 3 and 5 video uploads.', NOW()),
('Data Interpretation', 'bar', 'Which tutor alternated the number of students taught daily?', '{"labels": ["Mon", "Tue", "Wed", "Thu", "Fri"], "datasets": [{"label": "Sophia", "data": [8, 10, 8, 10, 8], "backgroundColor": "#9575CD"}, {"label": "James", "data": [9, 9, 9, 9, 9], "backgroundColor": "#A5D6A7"}]}', 'Sophia', 'James', 'Ella', 'Noah', 'Sophia’s student count alternated daily between 8 and 10.', NOW()),
('Data Interpretation', 'bar', 'Which ride-hailing driver alternated the number of rides completed?', '{"labels": ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5"], "datasets": [{"label": "Leo", "data": [12, 16, 12, 16, 12], "backgroundColor": "#BA68C8"}, {"label": "Mia", "data": [13, 14, 15, 16, 17], "backgroundColor": "#4DB6AC"}]}', 'Leo', 'Mia', 'Eric', 'Nina', 'Leo alternated between 12 and 16 rides each day.', NOW()),
('Data Interpretation', 'bar', 'Which technician alternated work orders completed per shift?', '{"labels": ["Shift 1", "Shift 2", "Shift 3", "Shift 4", "Shift 5"], "datasets": [{"label": "Hannah", "data": [6, 8, 6, 8, 6], "backgroundColor": "#81C784"}, {"label": "Jack", "data": [7, 7, 7, 7, 7], "backgroundColor": "#FFB74D"}]}', 'Hannah', 'Jack', 'Ruth', 'Kyle', 'Hannah alternated work order completions between 6 and 8.', NOW()),
('Data Interpretation', 'bar', 'Which platform alternated engagement levels every other day?', '{"labels": ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5"], "datasets": [{"label": "LinkUp", "data": [200, 250, 200, 250, 200], "backgroundColor": "#4FC3F7"}, {"label": "BuzzNow", "data": [210, 220, 230, 240, 250], "backgroundColor": "#F06292"}]}', 'LinkUp', 'BuzzNow', 'ClickRight', 'TrendSet', 'LinkUp alternated engagement levels between 200 and 250.', NOW());

INSERT INTO analytical (category, type, question, chart_data, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation, created_at) VALUES 
('Data Interpretation', 'bar', 'Which gym member alternated workout repetitions throughout the week?', '{"labels": ["Mon", "Tue", "Wed", "Thu", "Fri"], "datasets": [{"label": "Jake", "data": [20, 30, 20, 30, 20], "backgroundColor": "#4DB6AC"}, {"label": "Emma", "data": [25, 26, 27, 28, 29], "backgroundColor": "#FFD54F"}]}', 'Jake', 'Emma', 'Cole', 'Ruby', 'Jake alternated his reps between 20 and 30 each session.', NOW()),
('Data Interpretation', 'bar', 'Which bakery alternated its daily bread output?', '{"labels": ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5"], "datasets": [{"label": "Baker\'s Delight", "data": [100, 120, 100, 120, 100], "backgroundColor": "#BA68C8"}, {"label": "BreadHub", "data": [105, 110, 115, 120, 125], "backgroundColor": "#81C784"}]}', 'Baker\'s Delight', 'BreadHub', 'FlourPower', 'GrainWorks', 'Baker\'s Delight alternated output between 100 and 120 loaves.', NOW()),
('Data Interpretation', 'bar', 'Which security guard alternated shift logs consistently?', '{"labels": ["Shift 1", "Shift 2", "Shift 3", "Shift 4", "Shift 5"], "datasets": [{"label": "Carl", "data": [5, 7, 5, 7, 5], "backgroundColor": "#64B5F6"}, {"label": "Gwen", "data": [6, 6, 6, 6, 6], "backgroundColor": "#FF8A65"}]}', 'Carl', 'Gwen', 'Andy', 'Lana', 'Carl logged alternating shift counts of 5 and 7.', NOW()),
('Data Interpretation', 'bar', 'Which teacher alternated quiz counts across the semester?', '{"labels": ["Week 1", "Week 2", "Week 3", "Week 4", "Week 5"], "datasets": [{"label": "Mr. Hill", "data": [2, 3, 2, 3, 2], "backgroundColor": "#F06292"}, {"label": "Ms. Lee", "data": [3, 3, 3, 3, 3], "backgroundColor": "#AED581"}]}', 'Mr. Hill', 'Ms. Lee', 'Mr. Cruz', 'Ms. Tan', 'Mr. Hill alternated between 2 and 3 quizzes per week.', NOW()),
('Data Interpretation', 'bar', 'Which hospital alternated patient discharges over days?', '{"labels": ["Mon", "Tue", "Wed", "Thu", "Fri"], "datasets": [{"label": "St. Jude", "data": [18, 22, 18, 22, 18], "backgroundColor": "#9575CD"}, {"label": "Mercy Care", "data": [20, 21, 22, 23, 24], "backgroundColor": "#4DD0E1"}]}', 'St. Jude', 'Mercy Care', 'Riverway', 'Unity Health', 'St. Jude alternated discharges between 18 and 22 each day.', NOW());

INSERT INTO analytical (category, type, question, chart_data, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation, created_at) VALUES 
('Data Interpretation', 'bar', 'Which team alternated the number of tasks completed daily?', '{"labels": ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5"], "datasets": [{"label": "Team Orion", "data": [14, 18, 14, 18, 14], "backgroundColor": "#4FC3F7"}, {"label": "Team Vega", "data": [15, 16, 17, 18, 19], "backgroundColor": "#FDD835"}]}', 'Team Orion', 'Team Vega', 'Team Luna', 'Team Sol', 'Team Orion alternated between 14 and 18 tasks completed each day.', NOW()),
('Data Interpretation', 'bar', 'Which driver alternated the number of deliveries per shift?', '{"labels": ["Shift 1", "Shift 2", "Shift 3", "Shift 4", "Shift 5"], "datasets": [{"label": "David", "data": [10, 12, 10, 12, 10], "backgroundColor": "#81C784"}, {"label": "Alan", "data": [11, 12, 13, 14, 15], "backgroundColor": "#BA68C8"}]}', 'David', 'Alan', 'Maria', 'Lucas', 'David made alternating deliveries of 10 and 12 each shift.', NOW()),
('Data Interpretation', 'bar', 'Which department alternated their weekly meetings?', '{"labels": ["Week 1", "Week 2", "Week 3", "Week 4", "Week 5"], "datasets": [{"label": "HR", "data": [2, 3, 2, 3, 2], "backgroundColor": "#4DB6AC"}, {"label": "Finance", "data": [3, 3, 3, 3, 3], "backgroundColor": "#FF8A65"}]}', 'HR', 'Finance', 'IT', 'Legal', 'HR alternated between 2 and 3 meetings per week.', NOW()),
('Data Interpretation', 'bar', 'Which call center agent alternated the number of tickets resolved?', '{"labels": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], "datasets": [{"label": "Trish", "data": [22, 26, 22, 26, 22], "backgroundColor": "#7986CB"}, {"label": "Harvey", "data": [23, 24, 25, 26, 27], "backgroundColor": "#AED581"}]}', 'Trish', 'Harvey', 'Karen', 'Louis', 'Trish resolved tickets in an alternating 22–26 pattern.', NOW()),
('Data Interpretation', 'bar', 'Which fitness trainer alternated their daily session counts?', '{"labels": ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5"], "datasets": [{"label": "Nina", "data": [6, 9, 6, 9, 6], "backgroundColor": "#CE93D8"}, {"label": "Paul", "data": [7, 8, 9, 10, 11], "backgroundColor": "#4DD0E1"}]}', 'Nina', 'Paul', 'George', 'Lily', 'Nina alternated sessions between 6 and 9 across five days.', NOW());

INSERT INTO analytical (category, type, question, chart_data, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation, created_at) VALUES 
('Data Interpretation', 'bar', 'Which department had the highest number of customers in April?', '{"labels": ["Jan", "Feb", "Mar", "Apr", "May"], "datasets": [{"label": "Department A", "data": [150, 180, 170, 220, 190], "backgroundColor": "#FF5733"}, {"label": "Department B", "data": [130, 160, 180, 210, 200], "backgroundColor": "#33B5FF"}, {"label": "Department C", "data": [140, 190, 160, 180, 210], "backgroundColor": "#9C27B0"}]}', 'Department A', 'Department B', 'Department C', 'None of the above', 'Department A had the highest number of customers in April with 220.', NOW()),
('Data Interpretation', 'bar', 'Which store alternated its revenue pattern every other month?', '{"labels": ["Jan", "Feb", "Mar", "Apr", "May"], "datasets": [{"label": "Store 1", "data": [1000, 1500, 1000, 1500, 1000], "backgroundColor": "#CE93D8"}, {"label": "Store 2", "data": [1100, 1200, 1300, 1400, 1500], "backgroundColor": "#A5D6A7"}]}', 'Store 1', 'Store 2', 'Store 3', 'Store 4', 'Store 1 alternated between 1000 and 1500 in monthly revenue.', NOW()),
('Data Interpretation', 'bar', 'Which intern alternated perfectly between two productivity levels?', '{"labels": ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5"], "datasets": [{"label": "Ivy", "data": [60, 80, 60, 80, 60], "backgroundColor": "#EC407A"}, {"label": "Owen", "data": [65, 70, 75, 80, 85], "backgroundColor": "#42A5F5"}]}', 'Ivy', 'Owen', 'Lena', 'Mark', 'Ivy’s productivity alternated between 60 and 80 throughout the week.', NOW()),
('Data Interpretation', 'bar', 'Which gym member alternated workout repetitions throughout the week?', '{"labels": ["Mon", "Tue", "Wed", "Thu", "Fri"], "datasets": [{"label": "Jake", "data": [20, 30, 20, 30, 20], "backgroundColor": "#4DB6AC"}, {"label": "Emma", "data": [25, 26, 27, 28, 29], "backgroundColor": "#FFD54F"}]}', 'Jake', 'Emma', 'Cole', 'Ruby', 'Jake alternated his reps between 20 and 30 each session.', NOW()),
('Data Interpretation', 'bar', 'Which bakery alternated its daily bread output?', '{"labels": ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5"], "datasets": [{"label": "Baker\'s Delight", "data": [100, 120, 100, 120, 100], "backgroundColor": "#BA68C8"}, {"label": "BreadHub", "data": [105, 110, 115, 120, 125], "backgroundColor": "#81C784"}]}', 'Baker\'s Delight', 'BreadHub', 'FlourPower', 'GrainWorks', 'Baker\'s Delight alternated output between 100 and 120 loaves.', NOW());

INSERT INTO analytical (category, type, question, chart_data, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation, created_at) VALUES 
('Data Interpretation', 'bar', 'Which analyst submitted reports in an alternating pattern over weeks?', '{"labels": ["Week 1", "Week 2", "Week 3", "Week 4", "Week 5"], "datasets": [{"label": "Ethan", "data": [10, 15, 10, 15, 10], "backgroundColor": "#4FC3F7"}, {"label": "Mia", "data": [12, 13, 14, 15, 16], "backgroundColor": "#FFB74D"}]}', 'Ethan', 'Mia', 'Liam', 'Zoe', 'Ethan alternated between 10 and 15 reports weekly.', NOW()),
('Data Interpretation', 'bar', 'Which freelancer alternated weekly hours strictly?', '{"labels": ["Week 1", "Week 2", "Week 3", "Week 4", "Week 5"], "datasets": [{"label": "Nora", "data": [20, 30, 20, 30, 20], "backgroundColor": "#4DD0E1"}, {"label": "Tom", "data": [25, 26, 27, 28, 29], "backgroundColor": "#DCE775"}]}', 'Nora', 'Tom', 'Ella', 'Ray', 'Nora’s hours alternated between 20 and 30 each week.', NOW()),
('Data Interpretation', 'bar', 'Which bakery alternated its daily bread output?', '{"labels": ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5"], "datasets": [{"label": "Baker\'s Delight", "data": [100, 120, 100, 120, 100], "backgroundColor": "#BA68C8"}, {"label": "BreadHub", "data": [105, 110, 115, 120, 125], "backgroundColor": "#81C784"}]}', 'Baker\'s Delight', 'BreadHub', 'FlourPower', 'GrainWorks', 'Baker\'s Delight alternated output between 100 and 120 loaves.', NOW()),
('Data Interpretation', 'bar', 'Which city alternated its rainfall over the week?', '{"labels": ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5"], "datasets": [{"label": "City A", "data": [5, 10, 5, 10, 5], "backgroundColor": "#BA68C8"}, {"label": "City B", "data": [6, 7, 8, 9, 10], "backgroundColor": "#FF8A65"}]}', 'City A', 'City B', 'City C', 'City D', 'City A alternated rainfall values between 5mm and 10mm.', NOW()),
('Data Interpretation', 'bar', 'Which gym member alternated workout repetitions throughout the week?', '{"labels": ["Mon", "Tue", "Wed", "Thu", "Fri"], "datasets": [{"label": "Jake", "data": [20, 30, 20, 30, 20], "backgroundColor": "#4DB6AC"}, {"label": "Emma", "data": [25, 26, 27, 28, 29], "backgroundColor": "#FFD54F"}]}', 'Jake', 'Emma', 'Cole', 'Ruby', 'Jake alternated his reps between 20 and 30 each session.', NOW());

INSERT INTO analytical (category, type, question, chart_data, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation, created_at) VALUES 
('Data Interpretation', 'bar', 'Which security guard alternated shift logs consistently?', '{"labels": ["Shift 1", "Shift 2", "Shift 3", "Shift 4", "Shift 5"], "datasets": [{"label": "Carl", "data": [5, 7, 5, 7, 5], "backgroundColor": "#64B5F6"}, {"label": "Gwen", "data": [6, 6, 6, 6, 6], "backgroundColor": "#FF8A65"}]}', 'Carl', 'Gwen', 'Andy', 'Lana', 'Carl logged alternating shift counts of 5 and 7.', NOW()),
('Data Interpretation', 'bar', 'Which teacher alternated quiz counts across the semester?', '{"labels": ["Week 1", "Week 2", "Week 3", "Week 4", "Week 5"], "datasets": [{"label": "Mr. Hill", "data": [2, 3, 2, 3, 2], "backgroundColor": "#F06292"}, {"label": "Ms. Lee", "data": [3, 3, 3, 3, 3], "backgroundColor": "#AED581"}]}', 'Mr. Hill', 'Ms. Lee', 'Mr. Cruz', 'Ms. Tan', 'Mr. Hill alternated between 2 and 3 quizzes per week.', NOW()),
('Data Interpretation', 'bar', 'Which warehouse alternated its shipment volume each month?', '{"labels": ["Jan", "Feb", "Mar", "Apr", "May"], "datasets": [{"label": "Warehouse 1", "data": [700, 900, 700, 900, 700], "backgroundColor": "#7986CB"}, {"label": "Warehouse 2", "data": [800, 820, 840, 860, 880], "backgroundColor": "#FFD54F"}]}', 'Warehouse 1', 'Warehouse 2', 'Warehouse 3', 'Warehouse 4', 'Warehouse 1 alternated shipment volume between 700 and 900 units.', NOW()),
('Data Interpretation', 'bar', 'Which online course saw an alternating enrollment pattern?', '{"labels": ["Session 1", "Session 2", "Session 3", "Session 4", "Session 5"], "datasets": [{"label": "Course A", "data": [60, 80, 60, 80, 60], "backgroundColor": "#BA68C8"}, {"label": "Course B", "data": [65, 70, 75, 80, 85], "backgroundColor": "#81C784"}]}', 'Course A', 'Course B', 'Course C', 'Course D', 'Course A enrollment alternated between 60 and 80 students.', NOW()),
('Data Interpretation', 'bar', 'Which driver alternated the number of deliveries per shift?', '{"labels": ["Shift 1", "Shift 2", "Shift 3", "Shift 4", "Shift 5"], "datasets": [{"label": "David", "data": [10, 12, 10, 12, 10], "backgroundColor": "#81C784"}, {"label": "Alan", "data": [11, 12, 13, 14, 15], "backgroundColor": "#BA68C8"}]}', 'David', 'Alan', 'Maria', 'Lucas', 'David made alternating deliveries of 10 and 12 each shift.', NOW());

INSERT INTO analytical (category, type, question, chart_data, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation, created_at) VALUES 
('Data Interpretation', 'bar', 'Which department alternated their weekly meetings?', '{"labels": ["Week 1", "Week 2", "Week 3", "Week 4", "Week 5"], "datasets": [{"label": "HR", "data": [2, 3, 2, 3, 2], "backgroundColor": "#4DB6AC"}, {"label": "Finance", "data": [3, 3, 3, 3, 3], "backgroundColor": "#FF8A65"}]}', 'HR', 'Finance', 'IT', 'Legal', 'HR alternated between 2 and 3 meetings per week.', NOW()),
('Data Interpretation', 'bar', 'Which call center agent alternated the number of tickets resolved?', '{"labels": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], "datasets": [{"label": "Trish", "data": [22, 26, 22, 26, 22], "backgroundColor": "#7986CB"}, {"label": "Harvey", "data": [23, 24, 25, 26, 27], "backgroundColor": "#AED581"}]}', 'Trish', 'Harvey', 'Karen', 'Louis', 'Trish resolved tickets in an alternating 22–26 pattern.', NOW()),
('Data Interpretation', 'bar', 'Which fitness trainer alternated their daily session counts?', '{"labels": ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5"], "datasets": [{"label": "Nina", "data": [6, 9, 6, 9, 6], "backgroundColor": "#CE93D8"}, {"label": "Paul", "data": [7, 8, 9, 10, 11], "backgroundColor": "#4DD0E1"}]}', 'Nina', 'Paul', 'George', 'Lily', 'Nina alternated sessions between 6 and 9 across five days.', NOW()),
('Data Interpretation', 'bar', 'Which bakery alternated its daily bread output?', '{"labels": ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5"], "datasets": [{"label": "Baker\'s Delight", "data": [100, 120, 100, 120, 100], "backgroundColor": "#BA68C8"}, {"label": "BreadHub", "data": [105, 110, 115, 120, 125], "backgroundColor": "#81C784"}]}', 'Baker\'s Delight', 'BreadHub', 'FlourPower', 'GrainWorks', 'Baker\'s Delight alternated output between 100 and 120 loaves.', NOW()),
('Data Interpretation', 'bar', 'Which security guard alternated shift logs consistently?', '{"labels": ["Shift 1", "Shift 2", "Shift 3", "Shift 4", "Shift 5"], "datasets": [{"label": "Carl", "data": [5, 7, 5, 7, 5], "backgroundColor": "#64B5F6"}, {"label": "Gwen", "data": [6, 6, 6, 6, 6], "backgroundColor": "#FF8A65"}]}', 'Carl', 'Gwen', 'Andy', 'Lana', 'Carl logged alternating shift counts of 5 and 7.', NOW());

INSERT INTO analytical (category, type, question, chart_data, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation, created_at) VALUES 
('Data Interpretation', 'bar', 'Which department alternated their weekly meetings?', '{"labels": ["Week 1", "Week 2", "Week 3", "Week 4", "Week 5"], "datasets": [{"label": "HR", "data": [2, 3, 2, 3, 2], "backgroundColor": "#4DB6AC"}, {"label": "Finance", "data": [3, 3, 3, 3, 3], "backgroundColor": "#FF8A65"}]}', 'HR', 'Finance', 'IT', 'Legal', 'HR alternated between 2 and 3 meetings per week.', NOW()),
('Data Interpretation', 'bar', 'Which call center agent alternated the number of tickets resolved?', '{"labels": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], "datasets": [{"label": "Trish", "data": [22, 26, 22, 26, 22], "backgroundColor": "#7986CB"}, {"label": "Harvey", "data": [23, 24, 25, 26, 27], "backgroundColor": "#AED581"}]}', 'Trish', 'Harvey', 'Karen', 'Louis', 'Trish resolved tickets in an alternating 22–26 pattern.', NOW()),
('Data Interpretation', 'bar', 'Which fitness trainer alternated their daily session counts?', '{"labels": ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5"], "datasets": [{"label": "Nina", "data": [6, 9, 6, 9, 6], "backgroundColor": "#CE93D8"}, {"label": "Paul", "data": [7, 8, 9, 10, 11], "backgroundColor": "#4DD0E1"}]}', 'Nina', 'Paul', 'George', 'Lily', 'Nina alternated sessions between 6 and 9 across five days.', NOW()),
('Data Interpretation', 'bar', 'Which bakery alternated its daily bread output?', '{"labels": ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5"], "datasets": [{"label": "Baker\'s Delight", "data": [100, 120, 100, 120, 100], "backgroundColor": "#BA68C8"}, {"label": "BreadHub", "data": [105, 110, 115, 120, 125], "backgroundColor": "#81C784"}]}', 'Baker\'s Delight', 'BreadHub', 'FlourPower', 'GrainWorks', 'Baker\'s Delight alternated output between 100 and 120 loaves.', NOW()),
('Data Interpretation', 'bar', 'Which security guard alternated shift logs consistently?', '{"labels": ["Shift 1", "Shift 2", "Shift 3", "Shift 4", "Shift 5"], "datasets": [{"label": "Carl", "data": [5, 7, 5, 7, 5], "backgroundColor": "#64B5F6"}, {"label": "Gwen", "data": [6, 6, 6, 6, 6], "backgroundColor": "#FF8A65"}]}', 'Carl', 'Gwen', 'Andy', 'Lana', 'Carl logged alternating shift counts of 5 and 7.', NOW());

INSERT INTO analytical (category, type, question, chart_data, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation, created_at) VALUES 
('Data Interpretation', 'bar', 'Which intern alternated perfectly between two productivity levels?', '{"labels": ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5"], "datasets": [{"label": "Ivy", "data": [60, 80, 60, 80, 60], "backgroundColor": "#EC407A"}, {"label": "Owen", "data": [65, 70, 75, 80, 85], "backgroundColor": "#42A5F5"}]}', 'Ivy', 'Owen', 'Lena', 'Mark', 'Ivy’s productivity alternated between 60 and 80 throughout the week.', NOW()),
('Data Interpretation', 'bar', 'Which call center showed an alternating volume of customer calls?', '{"labels": ["Mon", "Tue", "Wed", "Thu", "Fri"], "datasets": [{"label": "Center East", "data": [120, 90, 120, 90, 120], "backgroundColor": "#AB47BC"}, {"label": "Center West", "data": [100, 110, 120, 130, 140], "backgroundColor": "#66BB6A"}]}', 'Center East', 'Center West', 'Center North', 'Center South', 'Center East alternated exactly between 120 and 90 calls.', NOW()),
('Data Interpretation', 'bar', 'Which marketing campaign had a back-and-forth trend in reach?', '{"labels": ["Week 1", "Week 2", "Week 3", "Week 4", "Week 5"], "datasets": [{"label": "Campaign Z", "data": [5000, 7000, 5000, 7000, 5000], "backgroundColor": "#FFCA28"}, {"label": "Campaign Y", "data": [5200, 5300, 5400, 5500, 5600], "backgroundColor": "#26C6DA"}]}', 'Campaign Z', 'Campaign Y', 'Campaign X', 'Campaign Q', 'Campaign Z switched between 5000 and 7000 reach every week.', NOW()),
('Data Interpretation', 'bar', 'Which delivery route showed alternating fuel usage each trip?', '{"labels": ["Trip 1", "Trip 2", "Trip 3", "Trip 4", "Trip 5"], "datasets": [{"label": "Route 5", "data": [30, 40, 30, 40, 30], "backgroundColor": "#29B6F6"}, {"label": "Route 8", "data": [32, 34, 36, 38, 40], "backgroundColor": "#EF5350"}]}', 'Route 5', 'Route 8', 'Route 3', 'Route 6', 'Route 5 alternated fuel usage perfectly between 30 and 40 liters.', NOW()),
('Data Interpretation', 'bar', 'Which student alternated their test scores every session?', '{"labels": ["Test 1", "Test 2", "Test 3", "Test 4", "Test 5"], "datasets": [{"label": "Sam", "data": [75, 85, 75, 85, 75], "backgroundColor": "#26A69A"}, {"label": "Alex", "data": [78, 79, 80, 81, 82], "backgroundColor": "#FF7043"}]}', 'Sam', 'Alex', 'Jamie', 'Taylor', 'Sam scored alternately 75 and 85 in a repeating pattern.', NOW());

INSERT INTO analytical (category, type, question, chart_data, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation, created_at) VALUES 
('Data Interpretation', 'bar', 'Which vendor alternated between high and low deliveries each month?', '{"labels": ["Jan", "Feb", "Mar", "Apr", "May"], "datasets": [{"label": "Vendor A", "data": [1000, 800, 1000, 800, 1000], "backgroundColor": "#7E57C2"}, {"label": "Vendor B", "data": [950, 960, 970, 980, 990], "backgroundColor": "#66BB6A"}]}', 'Vendor A', 'Vendor B', 'Vendor C', 'Vendor D', 'Vendor A followed a perfect up-down delivery cycle.', NOW()),
('Data Interpretation', 'bar', 'Which athlete’s performance alternated regularly during the tournament?', '{"labels": ["Round 1", "Round 2", "Round 3", "Round 4", "Round 5"], "datasets": [{"label": "Neil", "data": [22, 28, 22, 28, 22], "backgroundColor": "#5C6BC0"}, {"label": "Ryan", "data": [20, 21, 22, 23, 24], "backgroundColor": "#FFB74D"}]}', 'Neil', 'Ryan', 'Carl', 'Victor', 'Neil’s scores alternated consistently between 22 and 28.', NOW()),
('Data Interpretation', 'bar', 'Which intern alternated perfectly between two productivity levels?', '{"labels": ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5"], "datasets": [{"label": "Ivy", "data": [60, 80, 60, 80, 60], "backgroundColor": "#EC407A"}, {"label": "Owen", "data": [65, 70, 75, 80, 85], "backgroundColor": "#42A5F5"}]}', 'Ivy', 'Owen', 'Lena', 'Mark', 'Ivy’s productivity alternated between 60 and 80 throughout the week.', NOW()),
('Data Interpretation', 'bar', 'Which call center showed an alternating volume of customer calls?', '{"labels": ["Mon", "Tue", "Wed", "Thu", "Fri"], "datasets": [{"label": "Center East", "data": [120, 90, 120, 90, 120], "backgroundColor": "#AB47BC"}, {"label": "Center West", "data": [100, 110, 120, 130, 140], "backgroundColor": "#66BB6A"}]}', 'Center East', 'Center West', 'Center North', 'Center South', 'Center East alternated exactly between 120 and 90 calls.', NOW()),
('Data Interpretation', 'bar', 'Which marketing campaign had a back-and-forth trend in reach?', '{"labels": ["Week 1", "Week 2", "Week 3", "Week 4", "Week 5"], "datasets": [{"label": "Campaign Z", "data": [5000, 7000, 5000, 7000, 5000], "backgroundColor": "#FFCA28"}, {"label": "Campaign Y", "data": [5200, 5300, 5400, 5500, 5600], "backgroundColor": "#26C6DA"}]}', 'Campaign Z', 'Campaign Y', 'Campaign X', 'Campaign Q', 'Campaign Z switched between 5000 and 7000 reach every week.', NOW());

INSERT INTO analytical (category, type, question, chart_data, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation, created_at) VALUES 
('Data Interpretation', 'bar', 'Which team alternated the number of tasks completed daily?', '{"labels": ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5"], "datasets": [{"label": "Team Orion", "data": [14, 18, 14, 18, 14], "backgroundColor": "#4FC3F7"}, {"label": "Team Vega", "data": [15, 16, 17, 18, 19], "backgroundColor": "#FDD835"}]}', 'Team Orion', 'Team Vega', 'Team Luna', 'Team Sol', 'Team Orion alternated between 14 and 18 tasks completed each day.', NOW()),
('Data Interpretation', 'bar', 'Which driver alternated the number of deliveries per shift?', '{"labels": ["Shift 1", "Shift 2", "Shift 3", "Shift 4", "Shift 5"], "datasets": [{"label": "David", "data": [10, 12, 10, 12, 10], "backgroundColor": "#81C784"}, {"label": "Alan", "data": [11, 12, 13, 14, 15], "backgroundColor": "#BA68C8"}]}', 'David', 'Alan', 'Maria', 'Lucas', 'David made alternating deliveries of 10 and 12 each shift.', NOW()),
('Data Interpretation', 'bar', 'Which department alternated their weekly meetings?', '{"labels": ["Week 1", "Week 2", "Week 3", "Week 4", "Week 5"], "datasets": [{"label": "HR", "data": [2, 3, 2, 3, 2], "backgroundColor": "#4DB6AC"}, {"label": "Finance", "data": [3, 3, 3, 3, 3], "backgroundColor": "#FF8A65"}]}', 'HR', 'Finance', 'IT', 'Legal', 'HR alternated between 2 and 3 meetings per week.', NOW()),
('Data Interpretation', 'bar', 'Which call center agent alternated the number of tickets resolved?', '{"labels": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], "datasets": [{"label": "Trish", "data": [22, 26, 22, 26, 22], "backgroundColor": "#7986CB"}, {"label": "Harvey", "data": [23, 24, 25, 26, 27], "backgroundColor": "#AED581"}]}', 'Trish', 'Harvey', 'Karen', 'Louis', 'Trish resolved tickets in an alternating 22–26 pattern.', NOW()),
('Data Interpretation', 'bar', 'Which fitness trainer alternated their daily session counts?', '{"labels": ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5"], "datasets": [{"label": "Nina", "data": [6, 9, 6, 9, 6], "backgroundColor": "#CE93D8"}, {"label": "Paul", "data": [7, 8, 9, 10, 11], "backgroundColor": "#4DD0E1"}]}', 'Nina', 'Paul', 'George', 'Lily', 'Nina alternated sessions between 6 and 9 across five days.', NOW());

